elyra-ai/canvas

CONTRIBUTING.md
code-of-conduct.md

Governance updates

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/harness/src/client/App.js

Add option to switch off Create Supernode in context menu

---

canvas_modules/harness/cypress/integration/canvas/auto-node-placement.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/object-model-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/cypress/support/index.js

Implemented AutoNodePlacement Unit Test using Cypress framework

---

canvas_modules/common-canvas/src/common-canvas/local-storage.js

Check electron local storage availability first

---

canvas_modules/common-canvas/.npmignore
canvas_modules/common-canvas/package.json

Fix npmignore and update build number

---

canvas_modules/common-canvas/src/common-canvas/local-storage.js
canvas_modules/harness/src/client/components/custom-canvases/modeler-flows/modeler-flows-canvas.jsx

Minor changes to modeler flows prepackaged canvas

---

canvas_modules/common-canvas/src/common-canvas/local-storage.js

Use appropriate local storage identifier

---

canvas_modules/harness/cypress/integration/canvas/clipboard.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/context-menu-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/toolbar-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/cypress/support/index.js

Implemented Clipboard Unit Test using Cypress framework

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2.scss
canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2Canvas.json
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/constants.js
canvas_modules/harness/src/styles/index.scss

Add new explain2 example application

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

Dragging comment link should not highlight already linked node

---

canvas_modules/common-canvas/__tests__/object-model/object-model-upgrade-flow-test.js
canvas_modules/common-canvas/src/object-model/canvas-in-handler.js
canvas_modules/common-canvas/src/object-model/canvas-out-handler.js
canvas_modules/common-canvas/src/object-model/pipeline-in-handler.js
canvas_modules/common-canvas/src/object-model/pipeline-out-handler.js
canvas_modules/common-canvas/src/object-model/schemas-utils/schema-validator.js
canvas_modules/common-canvas/src/object-model/schemas/V3/pipeline-flow-v3-schema.json
canvas_modules/harness/test_resources/diagrams/commentColorCanvas.json
canvas_modules/harness/test_resources/diagrams/commentUnderlap.json
canvas_modules/harness/test_resources/diagrams/linkColorCanvas.json
canvas_modules/harness/test_resources/diagrams/modelerCanvas.json
canvas_modules/harness/test_resources/diagrams/multiPortsCanvas.json
canvas_modules/harness/test_resources/diagrams/titanicFlowCanvas.json
canvas_modules/harness/test_resources/diagrams/v2-commentColorCanvas.json
canvas_modules/harness/test_resources/diagrams/v2-commentUnderlap.json
canvas_modules/harness/test_resources/diagrams/v2-linkColorCanvas.json
canvas_modules/harness/test_resources/diagrams/v2-modelerCanvas.json
canvas_modules/harness/test_resources/diagrams/v2-multiPortsCanvas.json
canvas_modules/harness/test_resources/diagrams/x-modelerCanvas.json

Support op property for model and binding nodes

---

canvas_modules/common-canvas/__tests__/common-properties/controls/code-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/expression-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/code_paramDef.json
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/common-canvas/src/common-properties/constants/form-constants.js
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx
canvas_modules/harness/src/client/components/common-properties-components.jsx
canvas_modules/harness/src/client/constants/properties-documentation-constants.js
canvas_modules/harness/test_resources/parameterDefs/code_paramDef.json

Add new code control and support for rows in expression control

---

canvas_modules/harness/cypress/integration/canvas/context-menu.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/context-menu-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

Implemented Context Menu Unit Test using Cypress framework

---

canvas_modules/harness/cypress/integration/canvas/context-menu.js
canvas_modules/harness/cypress/integration/canvas/decorators.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/cypress/support/index.js

Implemented Decorators Unit Test using Cypress framework

---

canvas_modules/harness/cypress/integration/canvas/error-marker.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/object-model-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

Implemented Error Marker Unit Test using Cypress framework

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js

New connection node highlighting left switchd on

---

canvas_modules/harness/cypress/integration/canvas/external-drag-drop.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js

Implemented External Drag and Drop Unit Test using Cypress framework

---

canvas_modules/harness/cypress/integration/canvas/external-drag-drop.js
canvas_modules/harness/cypress/integration/canvas/extra-canvas.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/object-model-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/toolbar-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/cypress/support/properties/properties-cmds.js
canvas_modules/harness/package.json

Upgraded Cypress to 4.4.1 and Implemented ExtraCanvas Unit Test

---

canvas_modules/harness/cypress/integration/canvas/links.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js

**Please do not merge**
Need to review the code after following comments in `links.js` file - 
- Following code works fine on localhost but fails on travis build
- // TODO: Move node on canvas and verify updated link paths
permitted to submit under a different license), …

Implemented Links Unit Test using Cypress Framework

---

canvas_modules/harness/cypress/integration/canvas/links.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js

Fixed cypress command moveNodeToPosition

---

canvas_modules/harness/cypress/integration/canvas/extra-canvas.js
canvas_modules/harness/features/Drag.feature
canvas_modules/harness/features/ExtraCanvas.feature
canvas_modules/harness/features/Supernode.feature
canvas_modules/harness/features/Tips.feature
canvas_modules/harness/features/Toolbar.feature
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/components/sidepanel.jsx

Refactor cavas side panel code to make adding new controls easier

---

canvas_modules/harness/cypress/integration/canvas/comment.js
canvas_modules/harness/cypress/integration/canvas/context-menu.js
canvas_modules/harness/cypress/integration/canvas/links.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/keyboard-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/toolbar-cmds.js
canvas_modules/harness/cypress/support/index.js
canvas_modules/harness/package.json

TODO: Resize comment is not working
it. …

Upgraded Cypress to 4.5.0 and implemented Comments Unit Test

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/integration/canvas/comment.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js

Fix comment sizing tests

---

canvas_modules/harness/cypress/integration/canvas/drag.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

Skipped a test which worked on localhost but failed on Travis.
it. …

Implemented Drag Unit test in Cypress

---

canvas_modules/harness/cypress/integration/canvas/links.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js

Fix Cypress links test

---

canvas_modules/harness/src/client/components/sidepanel-api.jsx

Change URL used with test notification message

---

canvas_modules/harness/cypress/integration/canvas/auto-node-placement.js
canvas_modules/harness/cypress/integration/canvas/comment.js
canvas_modules/harness/cypress/integration/canvas/context-menu.js
canvas_modules/harness/cypress/integration/canvas/drag.js
canvas_modules/harness/cypress/integration/canvas/extra-canvas.js
canvas_modules/harness/cypress/integration/canvas/links.js
canvas_modules/harness/cypress/integration/canvas/nodes.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/keyboard-cmds.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/object-model-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/cypress/support/properties/properties-cmds.js
canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js

Implemented nodes unit test in Cypress

---

canvas_modules/harness/features/NotificationPanel.feature
canvas_modules/harness/features/Palette.feature

Fix Chimpy tests

---

canvas_modules/harness/cypress/integration/canvas/palette.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

Implemented Palette unit test in Cypress

---

canvas_modules/harness/cypress/integration/canvas/ports.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

Implemented Ports unit test in Cypress

---

canvas_modules/harness/cypress/integration/canvas/snap-to-grid.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js

Implemented SnapToGrid unit test in Cypress

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

Only fetch svg icons when needed

---

canvas_modules/harness/cypress/integration/canvas/auto-node-placement.js
canvas_modules/harness/cypress/integration/canvas/comment.js
canvas_modules/harness/cypress/integration/canvas/error-marker.js
canvas_modules/harness/cypress/integration/canvas/external-drag-drop.js
canvas_modules/harness/cypress/integration/canvas/nodes.js
canvas_modules/harness/cypress/integration/canvas/palette.js
canvas_modules/harness/cypress/integration/canvas/ports.js
canvas_modules/harness/cypress/integration/canvas/supernode.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/keyboard-cmds.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/object-model-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/toolbar-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

- Fixed travis build error in `comment.js` file
- Skipped 2 tests in Supernode.js file for now because `cy.ctrlOrCmdClickCommentInSupernode()` and `cy.ctrlOrCmdClickNodeInSupernode()` work on localhost but fail on travis
permitted to submit under a different license), …

Implemented Supernode unit test in Cypress

---

canvas_modules/common-canvas/src/common-properties/controls/radioset/radioset.scss
canvas_modules/harness/src/client/components/ctrl/CustomEffectsCtrl.jsx

Fix styling for disabled radioset buttons

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/common-canvas/src/tooltip/tooltip.jsx
canvas_modules/harness/src/client/components/common-properties-components.jsx
canvas_modules/harness/src/client/components/common-properties-conditions.jsx
scripts/source_scan.sh

Fix documentation isses in source code

---

canvas_modules/harness/cypress/integration/canvas/toolbar.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/toolbar-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

TODO: Skipped this test `Test for secondary toolbar resize` because for given viewport size, number of items in toolbar doesn't match with chimp tests.
(c) The contribution was provided …

Implemented Toolbar unit test in Cypress

---

canvas_modules/harness/cypress/integration/canvas/undo-redo.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/keyboard-cmds.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/object-model-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/cypress/support/properties/properties-cmds.js
canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js

Implemented Undo-Redo unit test in Cypress

---

canvas_modules/harness/cypress/integration/canvas/zoom.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

TODO: Fix the skipped test. 
it.
(d) I understand and agree that this …

Implemented Zoom unit test in Cypress

---

canvas_modules/common-canvas/src/toolbar/toolbar.jsx
canvas_modules/harness/src/client/App.js

Allow toolbar icons to be provided as JSX

---

canvas_modules/common-canvas/locales/common-properties/locales/eo.json

Fix escape for eo locale file

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

Improve drag behavior for nodes

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/integration/canvas/decorators.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

Enable path decorators on nodes and links

---

canvas_modules/common-canvas/__tests__/common-properties/controls/hidden-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/hidden_paramDef.json
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/constants/form-constants.js
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/harness/src/client/components/common-properties-components.jsx
canvas_modules/harness/src/client/constants/properties-documentation-constants.js
canvas_modules/harness/test_resources/parameterDefs/hidden_paramDef.json

Add support for hidden control

---

canvas_modules/common-canvas/__tests__/notification-panel/notification-panel-test.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/toolbar/toolbar.jsx
canvas_modules/harness/cypress/integration/canvas/decorators.js
canvas_modules/harness/cypress/integration/canvas/notifications.js
canvas_modules/harness/cypress/integration/properties/custom-controls.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/toolbar-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-api.jsx
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/styles/sidepanel.scss

Fixes:
- https://github.com/elyra-ai/canvas/issues/25
- https://github.com/elyra-ai/canvas/issues/104
New features:
- Optional clear all button
- Options to dismiss individual messages
- Spacing and structure for a subtitle
- Ability to open notification center when empty, with option to pass in a default empty message
- Option to keep notification center open when clicking elsewhere
- A close button
- Styling changes
license and I have the …

Update notification center

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-builder.jsx
canvas_modules/harness/cypress/.eslintrc.js
canvas_modules/harness/cypress/integration/canvas/decorators.js
canvas_modules/harness/cypress/integration/canvas/extra-canvas.js
canvas_modules/harness/cypress/integration/canvas/nodes.js
canvas_modules/harness/cypress/integration/canvas/notifications.js
canvas_modules/harness/cypress/integration/canvas/undo-redo.js
canvas_modules/harness/cypress/integration/properties/expression-control.js
canvas_modules/harness/cypress/integration/properties/structure-list-editor-table-control.js
canvas_modules/harness/cypress/integration/properties/structure-table-control.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/cypress/support/index.js
canvas_modules/harness/cypress/support/properties/expression-editor-cmds.js
canvas_modules/harness/cypress/support/properties/properties-cmds.js
canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js

This PR is for 3 Cypress files. Added 3 commits (1 per file). 
it. …

Implemented ExpressionControl, StructureListEditorTableControl, StructureTableControl unit tests in Cypress

---

LICENSE
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/constants/canvas-constants.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/.eslintrc.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/LICENSE
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/constant.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/event.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/index.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/noevent.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/transform.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/zoom.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-zoom.js
canvas_modules/harness/cypress/integration/canvas/toolbar.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/constants.js

(#109) Provide zoom type to hide negative coordinate space

---

canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss
canvas_modules/harness/src/styles/index.scss

Styling update for https://github.com/elyra-ai/canvas/issues/104
Replace fonts with Carbon typography tokens, centers the notification icon, adjusts spacing (accounting for line height introduced by typography tokens)
permitted to submit under a different license), as …

update notification center (styling)

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/constants.js

#128 Provide Canvas Underlay to make zoom behavior more obvious

---

canvas_modules/common-canvas/__tests__/common-properties/panels/column-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/panelConditions_paramDef.json
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/panel_paramDef.json
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/common-canvas/src/common-properties/constants/form-constants.js
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/panels/column/column.jsx
canvas_modules/common-canvas/src/common-properties/panels/column/column.scss
canvas_modules/common-canvas/src/common-properties/panels/column/index.js
canvas_modules/common-canvas/src/common-properties/panels/panels.scss
canvas_modules/harness/src/client/components/common-properties-components.jsx
canvas_modules/harness/src/client/constants/properties-documentation-constants.js
canvas_modules/harness/test_resources/parameterDefs/panelConditions_paramDef.json
canvas_modules/harness/test_resources/parameterDefs/panel_paramDef.json

#130 add support for multiple columns of panels

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#139 Only one <use> element shoud be added to images

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/diagram-canvas-d3.jsx
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/harness/cypress/integration/canvas/clipboard.js
canvas_modules/harness/cypress/support/canvas/context-menu-cmds.js

#141 Enable clipboard actions on the browser's Edit menu

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/ui-conditions-parser.js

#145 Provide a properties-controller method to return action control

---

canvas_modules/common-canvas/src/common-properties/ui-conditions/ui-conditions-parser.js

#145 Remove unused method from condition parser

---

canvas_modules/common-canvas/src/common-canvas/local-storage.js

Flow zoom and pan amounts not being saved correctly in desktop version

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/integration/canvas/zoom.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/utils-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx

#150 Pan canvas objects into view on open

---

.travis.yml

Addresses https://github.com/elyra-ai/canvas/issues/156
Upgrade node version in travis
person who certified (a), (b) or (c) and I …

#156 Upgrade node version to 12.18.2

---

canvas_modules/common-canvas/package.json
canvas_modules/harness/package.json

Addresses https://github.com/elyra-ai/canvas/issues/158
it.
(d) I …

#158 Update lodash to 4.17.19 for security

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss

#160 properties causes canvas div to jump off screen

---

canvas_modules/common-canvas/src/object-model/object-model.js

#162 nodeTemplate inputs and output ui_data is being deleted

---

canvas_modules/common-canvas/Gruntfile.js
canvas_modules/common-canvas/src/index.js
canvas_modules/common-canvas/webpack.config.js
canvas_modules/harness/Gruntfile.js
canvas_modules/harness/manifest.yml
canvas_modules/harness/src/common-canvas-dev.js
canvas_modules/harness/src/styles/canvas-customization.scss
canvas_modules/harness/src/styles/index.scss
canvas_modules/harness/webpack.config.dev.js

#173 fix common canvas css output

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/themes/light.scss
canvas_modules/common-canvas/webpack.config.js
canvas_modules/harness/src/common-canvas-dev.js

#173 Set default theme to gray10

---

canvas_modules/harness/cypress.json
canvas_modules/harness/cypress/integration/canvas/context-menu.js
canvas_modules/harness/cypress/integration/canvas/palette.js
canvas_modules/harness/cypress/integration/canvas/supernode.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js

Fixes https://github.com/elyra-ai/canvas/issues/176
it.
(d) I …

Cypress - CSS values should be in the compare range of +/- 2px

---

canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.scss

#178 Remove style override for carbon select control

---

canvas_modules/common-canvas/__tests__/common-properties/controls/list-test.js
canvas_modules/common-canvas/src/common-properties/controls/list/list.jsx
canvas_modules/harness/test_resources/parameterDefs/list_paramDef.json

#170 support list with no currentValue or default value set

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/__tests__/common-properties/utils/property-utils-test.js
canvas_modules/common-canvas/__tests__/test_resources/json/form-editstyle-test.json
canvas_modules/common-canvas/__tests__/test_resources/json/form-structure-test.json
canvas_modules/common-canvas/__tests__/test_resources/json/form-structure2-test.json
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structureeditor_paramDef.json
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structurelisteditor_paramDef.json
canvas_modules/common-canvas/src/common-properties/form/ControlInfo.js
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/form/ParameterInfo.js
canvas_modules/common-canvas/src/common-properties/form/StructureInfo.js
canvas_modules/common-canvas/src/common-properties/panels/summary/summary.jsx
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/common-canvas/src/common-properties/util/property-utils.js
canvas_modules/harness/test_resources/parameterDefs/structureeditor_paramDef.json
canvas_modules/harness/test_resources/parameterDefs/structurelisteditor_paramDef.json
canvas_modules/harness/test_resources/parameterDefs/structuretable_paramDef.json

#168 structures to return objects of parameter ids and value pairs

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-toolbar.jsx

#183 CommonCanvasToolbar should not alter props

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/harness/src/client/App_small.js
canvas_modules/harness/src/client/index.js

#185 Enable sample apps for toolbar change

---

canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx

Fixes: https://github.com/elyra-ai/canvas/issues/191
it.
(d) I …

#191 Notification Panel subtitle should allow object or string

---

canvas_modules/common-canvas/locales/toolbar/locales/en.json
canvas_modules/common-canvas/locales/toolbar/locales/eo.json
canvas_modules/common-canvas/src/common-canvas/common-canvas-toolbar.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-divider-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-overflow-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.jsx

#188 Enable toolbar for screen reader

---

canvas_modules/common-canvas/__tests__/common-canvas/common-canvas-toolbar-test.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-toolbar.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/harness/src/client/App_small.js
canvas_modules/harness/src/client/App_tiny.js

#193 Toolbar related issues with smaple apps (tiny and small)

---

canvas_modules/common-canvas/src/toolbar/toolbar.scss

#195 Toolbar icon label vertical positioning

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/common-canvas/diagram-canvas-d3.jsx
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/client/App.js

#202 Provide API method to pan objects to center of the canvas viewport

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/object-model/schemas/readme

#206 Use new pipeline-schemas version: 3.0.19

---

canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.scss
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/constants.js
canvas_modules/harness/src/styles/canvas-customization.scss

#208 Support ability to hookup custom components in the Toolbar

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx

Fixes https://github.com/elyra-ai/canvas/issues/216
it.
(d) I …

Translations in Expression Builder

---

canvas_modules/common-canvas/src/notification-panel/notification-panel.scss

Fixes https://github.com/elyra-ai/canvas/issues/230
it.
(d) I …

#230 Long notification message overflow for environments that don't support overflow-wrap: anywhere

---

canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx

Fixes https://github.com/elyra-ai/canvas/issues/232
it.
(d) I …

#232 Add a callback for notifications "Clear All" button

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

Fixes https://github.com/elyra-ai/canvas/issues/227
it.
(d) I …

#227 Add function to get palette node type for operators

---

canvas_modules/common-canvas/__tests__/common-properties/panels/subtabs-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/tab_paramDef.json
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.scss
canvas_modules/common-canvas/src/common-properties/panels/subtabs/index.js
canvas_modules/common-canvas/src/common-properties/panels/subtabs/subtabs.jsx
canvas_modules/common-canvas/src/common-properties/panels/subtabs/subtabs.scss
canvas_modules/harness/test_resources/parameterDefs/tab_paramDef.json

#246 support conditions in subtabs

---

canvas_modules/common-canvas/__tests__/common-properties/components/editor-form-test.js

Disabling a unit test which passes on localhost but fails on travis - https://github.com/elyra-ai/canvas/issues/258
person who …

Skipped a unit test - validate subtabs work correctly

---

canvas_modules/common-canvas/src/tooltip/tooltip.jsx

Fixes https://github.com/elyra-ai/canvas/issues/243
it.
(d) I …

Display tooltip for last palette node on screen

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/harness/src/client/App.js

#262 differentiate when closePropertiesDialog is called from 'Cancel' or 'Save'

---

canvas_modules/common-canvas/src/common-properties/components/properties-modal/properties-modal.scss
canvas_modules/common-canvas/src/common-properties/panels/control/control.scss
canvas_modules/common-canvas/src/common-properties/panels/panels.scss
canvas_modules/harness/cypress/integration/canvas/tips.js

 #266 reduce spacing for properties in modal 

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/src/common-properties/components/properties-modal/properties-modal.jsx
canvas_modules/common-canvas/src/common-properties/components/properties-modal/properties-modal.scss
canvas_modules/common-canvas/src/common-properties/constants/constants.js

 #269 map properties modal sizes to carbon modals 

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx

#263 custom labels for properties buttons

---

canvas_modules/common-canvas/src/common-properties/components/properties-buttons/properties-buttons.scss
canvas_modules/common-canvas/src/common-properties/components/wide-flyout/wide-flyout.scss

Fixes: https://github.com/elyra-ai/canvas/issues/282
it.
(d) I …

#282 Change properties-button height to 64px

---

canvas_modules/harness/cypress/support/canvas/toolbar-cmds.js
canvas_modules/harness/src/client/components/sidepanel-modal.jsx

Fixes: https://github.com/elyra-ai/canvas/issues/299
it.
(d) I …

#299 Accessibility support for common-properties configuration options

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/object-model/schemas-utils/schema-validator.js
canvas_modules/common-canvas/src/object-model/schemas/v1/palette-v1-schema.json
canvas_modules/common-canvas/src/object-model/schemas/v1/pipeline-flow-v1-schema.json
canvas_modules/harness/test_resources/diagrams/v1-allNodes.json
canvas_modules/harness/test_resources/diagrams/v1-bigCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-blankCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-commentColorCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-commentUnderlap.json
canvas_modules/harness/test_resources/diagrams/v1-customAttrsCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-decoratorCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-linkColorCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-manyLinks.json
canvas_modules/harness/test_resources/diagrams/v1-modelerCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-multiPortsCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-multiPortsCanvas2.json
canvas_modules/harness/test_resources/diagrams/v1-multiPortsCanvas3.json
canvas_modules/harness/test_resources/diagrams/v1-pipeline-flow-v1-example.json
canvas_modules/harness/test_resources/diagrams/v1-portsColorCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-radialCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-simpleCommonIconsCanvas.json

#302 Upgdrade jsonschema library to latest version

---

canvas_modules/common-canvas/__tests__/common-properties/panels/text-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/panel_paramDef.json
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/panels/text-panel/text-panel.jsx
canvas_modules/harness/test_resources/parameterDefs/panel_paramDef.json

#304 Text panels without descriptions shouldn't show text

---

canvas_modules/harness/cypress/integration/canvas/zoom.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx

Fixes: https://github.com/elyra-ai/canvas/issues/300
it.
(d) I …

#300 Accessibility support for common-canvas configuration options

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/common-canvas/diagram-canvas-d3.jsx
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss
canvas_modules/harness/cypress/integration/canvas/nodes.js
canvas_modules/harness/cypress/integration/canvas/undo-redo.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx

#308 Enable right-side flyout to appear below the toolbar

---

canvas_modules/harness/src/client/components/sidepanel-api.jsx

Fixes: https://github.com/elyra-ai/canvas/issues/307
it.
(d) I …

#307 Accessibility support for API configuration options

---

canvas_modules/common-canvas/src/common-properties/components/properties-buttons/properties-buttons.scss
canvas_modules/common-canvas/src/common-properties/components/wide-flyout/wide-flyout.scss
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss
canvas_modules/harness/cypress/integration/properties/structure-list-editor-table-control.js
canvas_modules/harness/cypress/integration/properties/structure-table-control.js
canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js

Fixes: https://github.com/elyra-ai/canvas/issues/311
Also adjusted structure table height - 
person who certified (a), (b) or (c) …

#311 Adjust Right side flyout height

---

canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-properties.jsx
canvas_modules/harness/src/client/components/sidepanel.jsx
canvas_modules/harness/test_resources/parameterDefs/textfield_paramDef.json

#315 Add validate option to test harness

---

scripts/publish_modules.sh

#138 Fix Travis message that is obscured

---

canvas_modules/common-canvas/__tests__/object-model/canvas-controller-api-test.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/redux/reducers/canvasinfo.js
canvas_modules/common-canvas/src/object-model/redux/reducers/comments.js
canvas_modules/common-canvas/src/object-model/redux/reducers/links.js

#326 Add new canvas controller APIs to modify canvas objects

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#329 Not able to attach a node as target on a detached link

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/__tests__/common-properties/uiItems-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/common-properties/locales/eo.json
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx

Fixes: https://github.com/elyra-ai/canvas/issues/319
To test this PR -
1. Turn on VoiceOver (command + F5)
2. Open rotor (control + option + u)
3. Use left-right arrow keys to open Landmark menu
in the file; …

#319 Add landmark role for common-properties

---

canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.scss

Fixes: https://github.com/elyra-ai/canvas/issues/343
it.
(d) I …

#343 Fixed dropdown menu border blocked by Close button

---

canvas_modules/common-canvas/__tests__/object-model/canvas-controller-api-test.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-links.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/pipeline-out-handler.js
canvas_modules/harness/cypress/integration/canvas/decorators.js
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached.scss
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detachedCanvas.json

Link dec position

---

canvas_modules/common-canvas/__tests__/object-model/canvas-controller-api-test.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/redux/reducers/canvasinfo.js
canvas_modules/common-canvas/src/object-model/redux/reducers/nodes.js

357 Port addition/deletion UI render bugs

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/common-canvas/src/palette/palette-content-grid-node.jsx
canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx

#360 Wide node labels truncated when displayed as part of ghost image

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#167 Paste button is always enabled

---

canvas_modules/common-canvas/package.json

#255 Update minor version for new feature v9.2.0

---

canvas_modules/harness/src/client/components/common-properties-components.jsx
canvas_modules/harness/src/client/constants/properties-documentation-constants.js

#359 readonlyTable documentation

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.scss

Fixes cursor color for https://github.com/elyra-ai/canvas/issues/368 …

#368 Update CodeMirror cursor

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js

#389 propertyListener return values as object if the parameter structureType is object

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-links.js
canvas_modules/harness/cypress/integration/canvas/links.js
canvas_modules/harness/cypress/integration/canvas/nodes.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#387 Adapt overlapping link algorithm to elbow link type

---

canvas_modules/common-canvas/__tests__/test_resources/json/supernodeWithoutSubPipeline.json
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/object-model/pipeline-in-handler.js
canvas_modules/harness/test_resources/diagrams/allTypesCanvas.json
canvas_modules/harness/test_resources/diagrams/detachedLinksCanvas.json
canvas_modules/harness/test_resources/diagrams/pipelineFlowExample.json
canvas_modules/harness/test_resources/diagrams/stylesCanvas.json

#385 Saved pipelineFlow should store valid zoom amount

---

canvas_modules/common-canvas/package.json

#399 Use latest pipeline-schmeas module

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/.eslintrc.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/constant.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/event.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/noevent.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/zoom.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#401 Support D3 v6.2

---

.github/workflows/publish.yml
scripts/publish_modules.sh

#394 Fix publish action

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/cypress/integration/canvas/zoom.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx

#405 Ability to position nodes on the canvas during componentDidMount

---

canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx

#410 setPropertyValues() should convert input values into the internal format

---

canvas_modules/harness/cypress/integration/canvas/auto-layout-dagre.js
canvas_modules/harness/cypress/integration/canvas/auto-node-placement.js
canvas_modules/harness/cypress/integration/canvas/comment.js
canvas_modules/harness/cypress/integration/canvas/drag.js
canvas_modules/harness/cypress/integration/canvas/error-marker.js
canvas_modules/harness/cypress/integration/canvas/external-drag-drop.js
canvas_modules/harness/cypress/integration/canvas/extra-canvas.js
canvas_modules/harness/cypress/integration/canvas/nodes.js
canvas_modules/harness/cypress/integration/canvas/notifications.js
canvas_modules/harness/cypress/integration/canvas/palette.js
canvas_modules/harness/cypress/integration/canvas/ports.js
canvas_modules/harness/cypress/integration/canvas/snap-to-grid.js
canvas_modules/harness/cypress/integration/canvas/supernode.js
canvas_modules/harness/cypress/integration/canvas/tips.js
canvas_modules/harness/cypress/integration/canvas/toolbar.js
canvas_modules/harness/cypress/integration/canvas/undo-redo.js
canvas_modules/harness/package.json

#403 Support Cypress v6.1.0

---

canvas_modules/harness/src/styles/properties.scss

Fixes https://github.com/elyra-ai/canvas/issues/413
it.
(d) I …

#413 Change background color in properties documentation

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js

#415 Refactor common canvas and svg-canvas-d3 initial render function

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/util/property-utils.js

#410 add null checks

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/redux/reducers/canvasinfo.js

#420 Remove zoomPipeline method and refactor

---

canvas_modules/common-canvas/__tests__/common-properties/components/control-item-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/checkboxset-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/readonlytable-test.js
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss
canvas_modules/common-canvas/src/common-properties/controls/checkboxset/checkboxset.jsx
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/controls.scss

Fixes https://github.com/elyra-ai/canvas/issues/391
it.
(d) I …

#391 Checkboxset control should be accessible

---

canvas_modules/common-canvas/__tests__/common-properties/controls/structureeditor-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structurelisteditor-test.js
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/datefield/datefield.jsx
canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx
canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.scss
canvas_modules/common-canvas/src/common-properties/controls/passwordfield/passwordfield.jsx

Fixes https://github.com/elyra-ai/canvas/issues/423
it.
(d) I …

#423 Datefield, Numberfield, Spinner, Passwordfield controls are accessible

---

canvas_modules/common-canvas/__tests__/common-properties/controls/oneofselect-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/oneofselect_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx
canvas_modules/common-canvas/src/common-properties/form/ControlInfo.js
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/form/ParameterInfo.js
canvas_modules/harness/src/client/components/common-properties-components.jsx
canvas_modules/harness/src/client/constants/properties-documentation-constants.js
canvas_modules/harness/test_resources/parameterDefs/oneofselect_paramDef.json

#427 dropdown support to enter custom value

---

canvas_modules/common-canvas/__tests__/common-properties/controls/hidden-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structureeditor-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structurelisteditor-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/toggletext-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/common-properties/locales/eo.json
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/textarea/textarea.jsx
canvas_modules/common-canvas/src/common-properties/controls/textfield/textfield.jsx
canvas_modules/common-canvas/src/common-properties/controls/timefield/timefield.jsx
canvas_modules/common-canvas/src/common-properties/controls/toggletext/toggletext.jsx

Fixes https://github.com/elyra-ai/canvas/issues/426
Screen reader reads following for toggle text buttons -
- On Icon On, button, toggletext, Group
- Ascending, button, toggletext without icons, group
- Descending Icon Descending, button, toggletext Default, group …

#426 Textarea, Textfield, Timefield, Toggletext controls are accessible

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/list_paramDef.json
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/custom/condition-ops/customNonEmptyListLessThan.js
canvas_modules/harness/test_resources/parameterDefs/list_paramDef.json

#434 add custom condition operation in test harness for properties

---

canvas_modules/common-canvas/package.json
canvas_modules/harness/package.json

Fixes https://github.com/elyra-ai/canvas/issues/408
it.
(d) I …

#408 Remove node-sass dependency

---

canvas_modules/common-canvas/src/common-canvas/diagram-canvas-d3.jsx
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#439 Performance issues while dragging new node over links in canvas

---

canvas_modules/harness/src/client/App.js

Fixes https://github.com/elyra-ai/canvas/issues/445
Added `aria-label` for links in test harness header …

#445 Test harness header is accessible

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-nodes.js

#449 Refactor canvas utility functions

---

canvas_modules/harness/package.json

#457 Update to latest Cypress version: 6.3.0

---

canvas_modules/common-canvas/src/object-model/redux/reducers/links.js
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx

#453 Undo of link deletion doesn't bring back link decorations

---

canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/schema-validator/properties-schema-validator.js
canvas_modules/harness/test_resources/parameterDefs/textfield_paramDef.json

Cou properties schema validator default setting

---

canvas_modules/harness/src/client/App.js

#462 Improve test harness code that creates externally dragged objects

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/styles/canvas-customization.scss
canvas_modules/harness/test_resources/diagrams/linkColorCanvas.json
canvas_modules/harness/test_resources/diagrams/v1-linkColorCanvas.json
canvas_modules/harness/test_resources/diagrams/v2-linkColorCanvas.json
canvas_modules/harness/test_resources/diagrams/x-linkColorCanvas.json

#468 Set classname API should set class name on group objects

---

canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx

Fixes https://github.com/elyra-ai/canvas/issues/472
it.
(d) I …

#472 Fixed filtering error in structurelisteditor

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#470 Selection of comment to node links difficult

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached.scss
canvas_modules/harness/src/styles/canvas-customization.scss

#474 Link decorators should appear under link handles

---

canvas_modules/harness/assets/images/down-triangle.svg
canvas_modules/harness/assets/images/up-triangle.svg
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached.scss

#477 Create sample to pass a fill color to an SVG image decorator

---

canvas_modules/common-canvas/__tests__/common-properties/controls/toggletext-test.js
canvas_modules/common-canvas/__tests__/common-properties/defaults-test.js
canvas_modules/common-canvas/src/common-properties/controls/toggletext/toggletext.jsx
canvas_modules/common-canvas/src/common-properties/controls/toggletext/toggletext.scss

Fixes https://github.com/elyra-ai/canvas/issues/479
it.
(d) I …

#479 Toggletext button in carbon style

---

canvas_modules/common-canvas/__tests__/common-properties/components/fieldpicker-test.js
canvas_modules/common-canvas/__tests__/common-properties/components/flexibletable-test.js
canvas_modules/common-canvas/__tests__/common-properties/components/moveabletablerows-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/hidden-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumns-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/someofselect-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/common-properties/locales/eo.json
canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.jsx
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/components/moveable-table-rows/moveable-table-rows.jsx
canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/list/list.jsx
canvas_modules/common-canvas/src/common-properties/controls/selectcolumns/selectcolumns.jsx
canvas_modules/common-canvas/src/common-properties/controls/someofselect/someofselect.jsx
canvas_modules/common-canvas/src/common-properties/controls/structureeditor/structureeditor.jsx
canvas_modules/common-canvas/src/common-properties/panels/summary/summary.jsx

Fixes https://github.com/elyra-ai/canvas/issues/481
it.
(d) I …

#481 Someofselect, Selectcolumns, abstract-table, Fieldpicker controls are accessible

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-nodes.js
canvas_modules/common-canvas/src/object-model/canvas-in-handler.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/harness/cypress/integration/canvas/supernode.js
canvas_modules/harness/cypress/integration/canvas/zoom.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/src/client/components/custom-canvases/blue-ellipses/blue-ellipses-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/blue-ellipses/blue-ellipses.scss
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached.scss
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detachedCanvas.json
canvas_modules/harness/src/client/components/custom-canvases/explain/explain-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain/explain.scss
canvas_modules/harness/src/client/components/custom-canvases/explain/explainCanvas.json
canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2.scss
canvas_modules/harness/src/client/components/custom-canvases/flows/flows-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/streams/streams.json
canvas_modules/harness/src/client/components/custom-canvases/tables/tables-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/tables/tables.scss
canvas_modules/harness/src/client/components/custom-canvases/tables/tablesCanvas.json
canvas_modules/harness/test_resources/diagrams/decoratorCanvas.json

#464 Allow multi-line text for node labels and text decorators

---

scripts/publish_modules.sh

#487 Revert npm version command to build patches

---

canvas_modules/harness/src/client/components/sidepanel-canvas.jsx

#489 Node Format Type option in test harness not working

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/src/client/App_auto_ai.js
canvas_modules/harness/src/client/components/custom-canvases/blue-ellipses/blue-ellipses-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain/explain-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/flows/flows-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/streams/streams-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/tables/tables-canvas.jsx

#491 Fix center positioning for node elements in example Streams application

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-nodes.js
canvas_modules/harness/src/client/components/custom-canvases/flows/flows-canvas.jsx

#495 Design changes needed for editable labels

---

canvas_modules/common-canvas/package.json
canvas_modules/harness/package.json

Fixes https://github.com/elyra-ai/canvas/issues/498
it.
(d) I …

#498 Upgrade lodash to secure version

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/harness/cypress/integration/canvas/node-cardinalities.js
canvas_modules/harness/test_resources/diagrams/cardinalityCanvas.json

#533 Maximum cardinality of 0 on input port ignored

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached.scss
canvas_modules/harness/src/styles/canvas-customization.scss

#535 Remove hover from outline and put it on node groups

---

canvas_modules/common-canvas/__tests__/common-properties/controls/textfield-test.js
canvas_modules/common-canvas/src/common-properties/controls/textfield/textfield.jsx

Fixes https://github.com/elyra-ai/canvas/issues/505
it.
(d) I …

#505 handle undefined default textinput

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-nodes.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/cypress/integration/canvas/node-labels.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx

#537 Allow for customization of node name max length

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx

#539 Allow customization of arrow heads

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#541 Connecting nodes in in-place supernode doesn't work

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#545 Text decoration class name not updated correctly

---

canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/redux/reducers/links.js

#549 Links Name and other attrs not copied and pasted from clipboard

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js

#551 Allow multiple association links between nodes

---

canvas_modules/common-canvas/__tests__/common-properties/controls/multiselect-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/oneofselect-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumn-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/selectschema-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js
canvas_modules/common-canvas/__tests__/common-properties/operators/dm-condition-operators-test.js
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx
canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx
canvas_modules/common-canvas/src/common-properties/util/property-utils.js

Fix https://github.com/elyra-ai/canvas/issues/553
it.
(d) I …

#553 Oneofselect, multiselect, selectschema, selectcolumn controls are accessible

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss

#561 Node label is highlighted when node if double clicked

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/package.json

#559 Cannot add new nodes after dropping a node on a link

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/object-model/canvas-in-handler.js
canvas_modules/common-canvas/src/object-model/schemas-utils/schema-validator.js

#563 Remove check for json_schema with http in schema validation code

---

canvas_modules/common-canvas/__tests__/_utils_/property-utils.js
canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structurelisteditor-test.js
canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structurelisteditor_paramDef.json
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/harness/test_resources/parameterDefs/structurelisteditor_paramDef.json

Cou complex types default objects

---

canvas_modules/common-canvas/src/common-properties/schema-validator/properties-schema-validator.js

#570 Prefix https for properties schema validator

---

canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.scss

Fixes https://github.com/elyra-ai/canvas/issues/582
it.
(d) I …

#582 Using sentence style for column headers

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#578 Allow nodes to be dragged long distances in fullscreen mode

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-properties.jsx

#584 Add configuration options to always apply changes

---

canvas_modules/harness/src/client/App.js

#591 Add 'Download Palette' button to test harness

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#594 Palette node template cardinality max of zero insertable into link

---

canvas_modules/common-canvas/src/palette/palette-content-grid-node.jsx
canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/harness/test_resources/palettes/supernodePalette.json

#596 Supernode icon dosn't show in palette when icon === useDefaultIcon

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached.scss

#598 Minor supernode enhancements

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js
canvas_modules/common-canvas/src/palette/palette-flyout-content-category.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-content.jsx
canvas_modules/harness/cypress/integration/canvas/auto-node-placement.js
canvas_modules/harness/cypress/integration/canvas/palette.js

#604 Allow multiple palette sections to be open at the same time

---

canvas_modules/common-canvas/__tests__/common-properties/controls/expression-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/common-properties/locales/eo.json
canvas_modules/common-canvas/src/common-properties/actions.js
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-builder.jsx
canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx
canvas_modules/common-canvas/src/common-properties/controls/expression/expressionInfo-parser.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/common-canvas/src/common-properties/properties-store.js
canvas_modules/common-canvas/src/common-properties/reducers/component-metadata.js
canvas_modules/harness/cypress/integration/properties/expression-control.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-properties.jsx

#613 Fix expression validation handling

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
scripts/publish_modules.sh

#617 Double image displayed after image field in node updated

---

canvas_modules/common-canvas/__tests__/common-properties/components/fieldpicker-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/list-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumns-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/someofselect-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/common-properties/locales/eo.json
canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.jsx
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx
canvas_modules/common-canvas/src/common-properties/controls/list/list.jsx
canvas_modules/common-canvas/src/common-properties/controls/selectcolumns/selectcolumns.jsx
canvas_modules/common-canvas/src/common-properties/controls/someofselect/someofselect.jsx
canvas_modules/common-canvas/src/common-properties/util/property-utils.js

Fixes https://github.com/elyra-ai/canvas/issues/619
Reverted changes in https://github.com/elyra-ai/canvas/commit/302ead3ebcfcc672439993f128160ae60f40d328#diff-6a74ae667bc839b609875b48b841ab0a1270614d6857a11999f7ebde8bd3e6a2 …

#619 Using table name in row checkbox labels

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js
canvas_modules/common-canvas/package.json

#625 Remove uneeded npm module from package.json

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/redux/reducers/palette.js
canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-utils.js
canvas_modules/harness/src/client/components/custom-canvases/logic/logicCanvas.json

#630 Palette search string including spaces adds extra characters

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js

#634 Fix issue where hidden values need to be revalidated

---

canvas_modules/common-canvas/src/common-properties/components/moveable-table-rows/moveable-table-rows.scss

Fixes https://github.com/elyra-ai/canvas/issues/644
it.
(d) I …

#644 Removed padding in Moveable row tables

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/textarea-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/textfield-test.js
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/textarea/textarea.jsx
canvas_modules/common-canvas/src/common-properties/controls/textfield/textfield.jsx
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-properties.jsx

Fixes https://github.com/elyra-ai/canvas/issues/642
Test harness - …

#642 Added config options maxLengthForMultiLineControls and maxLengthForSingleLineControls in propertiesConfig

---

canvas_modules/common-canvas/__tests__/common-properties/controls/multiselect-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/multiselect_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx
canvas_modules/harness/test_resources/parameterDefs/multiselect_paramDef.json

#510 multiselect filter enum workaround

---

canvas_modules/common-canvas/src/common-properties/controls/controls.scss

Fixes https://github.com/elyra-ai/canvas/issues/650
it.
(d) I …

#650 Remove padding when action is hidden

---

canvas_modules/common-canvas/__tests__/common-canvas/common-canvas-toolbar-test.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-toolbar.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss
canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.scss

Fixes https://github.com/elyra-ai/canvas/issues/652
it.
(d) I …

#652 Updated notification panel styling

---

canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx

Fixes https://github.com/elyra-ai/canvas/issues/661
it.
(d) I …

#661 Fixed translations in multiselect control

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/pipeline-in-handler.js
canvas_modules/common-canvas/src/object-model/pipeline-out-handler.js
canvas_modules/harness/cypress/integration/canvas/clipboard.js
canvas_modules/harness/cypress/integration/canvas/links.js
canvas_modules/harness/test_resources/diagrams/detachedLinksCanvas.json

#640 Allow outputs from exit binding node

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/test_resources/diagrams/externalMainCanvas.json

#666 Comments having internal error when sized

---

canvas_modules/common-canvas/src/common-properties/controls/readonly/readonly.jsx
canvas_modules/common-canvas/src/common-properties/panels/summary/summary.jsx
canvas_modules/common-canvas/src/tooltip/tooltip.jsx

#668 Display tooltips only if text are truncated

---

canvas_modules/common-canvas/__tests__/common-properties/controls/numberfield-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/spinner-test.js
canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx

Fixes https://github.com/elyra-ai/canvas/issues/675
it.
(d) I …

#675 Remove increment/decrement buttons from numberfield control and set them on spinner control

---

canvas_modules/common-canvas/__tests__/object-model/object-model-upgrade-palette-test.js
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/pipeline-in-handler.js
canvas_modules/common-canvas/src/object-model/pipeline-out-handler.js
canvas_modules/harness/cypress/integration/canvas/node-exit-binding-output.js
canvas_modules/harness/test_resources/diagrams/detachedLinksCanvas.json
canvas_modules/harness/test_resources/palettes/bindingWithOutputPalette.json

#683 Allow outputs for exit binding nodes

---

canvas_modules/common-canvas/src/palette/palette.scss

#685 Palette Search field text and icon spacing adjustments

---

canvas_modules/common-canvas/__tests__/common-properties/operators/contains-test.js
canvas_modules/common-canvas/__tests__/common-properties/operators/notContains-test.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/condition-ops/contains.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/condition-ops/notContains.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js

#687 Update contains and notContains logic for arrays

---

scripts/publish_modules.sh

#689 Increment version major number

---

canvas_modules/harness/src/client/constants/properties-documentation-constants.js

Fixes https://github.com/elyra-ai/canvas/issues/691
it.
(d) I …

#691 Fixed spinner control documentation

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/integration/canvas/supernode.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/object-model-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
scripts/publish_modules.sh

#697 CanvasController.displaySubPipeline not working correctly

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js

Fixes https://github.com/elyra-ai/canvas/issues/695
it.
(d) I …

#695 form object should not have property whose value is undefined

---

canvas_modules/common-canvas/src/command-actions/createSuperNodeAction.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js

#700 Refactor supernode code

---

scripts/publish_modules.sh

#703 Build minor version

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx

#673 Callback after properties values and messages are set

---

canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/tables/tables-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/tables/tablesCanvas.json

#710 Fix issues in Explain 2 and Tables sample app

---

canvas_modules/common-canvas/src/index.js
canvas_modules/common-canvas/webpack.config.js

#712 Export tooltip to be reused by other tools

---

canvas_modules/common-canvas/src/command-actions/deleteObjectsAction.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/harness/cypress/integration/canvas/supernode-external.js

#714 Undo of deletion of external supernode not working

---

canvas_modules/common-canvas/__tests__/command-actions/display-sub-pipeline-action-test.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/harness/cypress/integration/canvas/supernode.js

#718 Refactor object model code referencing supernode pipelines

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js
canvas_modules/common-canvas/__tests__/palette/palette-test.js
canvas_modules/common-canvas/src/palette/palette-dialog-content-categories.jsx
canvas_modules/common-canvas/src/palette/palette-dialog-content-category.jsx
canvas_modules/common-canvas/src/palette/palette-dialog-content.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-content-category.jsx

#725 Added data-id attribute to palette categories

---

canvas_modules/common-canvas/__tests__/common-properties/controls/structurelisteditor-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structurelisteditor_paramDef.json
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.scss
canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.scss
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.scss
canvas_modules/harness/test_resources/parameterDefs/structurelisteditor_paramDef.json

#720 Remove usage of rgba(token, value) from scss

---

canvas_modules/common-canvas/src/common-properties/controls/readonly/readonly.scss

#727 Content in readonly control is selectable

---

canvas_modules/common-canvas/__tests__/common-properties/conditions/alerts-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/numberfield-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/numberfield_paramDef.json
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/form/ParameterInfo.js
canvas_modules/harness/test_resources/parameterDefs/numberfield_paramDef.json

Fixes https://github.com/elyra-ai/canvas/issues/729
it.
(d) I …

#729 Display Number generator label using resource_key

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structuretable_paramDef.json
canvas_modules/common-canvas/src/common-properties/form/ParameterInfo.js
canvas_modules/harness/test_resources/parameterDefs/structuretable_paramDef.json

#733 Strip off leading and trailing spaces

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#745 Change data link arrow head to correct default size

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-toolbar.jsx
canvas_modules/harness/cypress/integration/canvas/toolbar.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/constants.js

#747 Support override auto enablement of toolbar buttons

---

canvas_modules/common-canvas/__tests__/object-model/canvas-controller-api-test.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#749 Implement getCurrentPipelineId canvas controller method

---

canvas_modules/common-canvas/__tests__/.eslintrc.js
canvas_modules/common-canvas/__tests__/common-properties/controls/radioset-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/radio_paramDef.json
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/eslint-config-canvas/index.js
canvas_modules/harness/test_resources/parameterDefs/radio_paramDef.json

#759 Inline table enums should default to oneofselect

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/tooltip/tooltip-wrapper.jsx
canvas_modules/common-canvas/src/tooltip/tooltip.scss
canvas_modules/harness/cypress/integration/canvas/tips.js
canvas_modules/harness/cypress/support/canvas/toolbar-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#761 Use definition tooltip styling and 200ms delay for canvas tooltips

---

canvas_modules/common-canvas/__tests__/common-properties/conditions/conditional-default-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/defaults_paramDef.json
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/ui-conditions.js
canvas_modules/harness/test_resources/parameterDefs/CLEM_FilterRows_paramDef.json
canvas_modules/harness/test_resources/parameterDefs/defaults_paramDef.json

Fixes #755 
Updated `defaults_paramDef.json` in test harness -
it. …

#755 Support conditional defaults in common-properties

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#769 Uncaught TypeError: can't access property findIndex, t is undefined

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/cc-tooltip.jsx
canvas_modules/common-canvas/src/common-canvas/constants/canvas-constants.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/config-utils.js
canvas_modules/common-canvas/src/tooltip/tooltip.jsx
canvas_modules/harness/cypress/integration/canvas/decorators.js
canvas_modules/harness/cypress/integration/canvas/tips.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached.scss
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/constants.js

#771 Implement tooltip for link and node decorations

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

775 Console error dragging detached link

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js
canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/common-canvas/src/palette/palette-dialog-content-grid-node.jsx
canvas_modules/harness/cypress/integration/canvas/palette.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#777 Added data-id attribute to nodes in palette

---

canvas_modules/harness/package.json
canvas_modules/harness/src/client/App.js

#784 replace react file with js file

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/__tests__/common-properties/components/main-editor-proprties-button-test.js
canvas_modules/common-canvas/__tests__/common-properties/conditions/alerts-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/datefield-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/timefield-test.js
canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/__tests__/flow-validation/flow-validation-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/common-properties/locales/eo.json

#790 Updated required message in properties

---

canvas_modules/common-canvas/__tests__/command-actions/size-and-position-objects-action-test.js
canvas_modules/common-canvas/__tests__/common-canvas/supernode-test.js
canvas_modules/common-canvas/locales/common-canvas/locales/en.json
canvas_modules/common-canvas/locales/common-canvas/locales/eo.json
canvas_modules/common-canvas/src/command-actions/collapseSuperNodeInPlaceAction.js
canvas_modules/common-canvas/src/command-actions/deconstructSuperNodeAction.js
canvas_modules/common-canvas/src/command-actions/expandSuperNodeInPlaceAction.js
canvas_modules/common-canvas/src/command-actions/sizeAndPositionObjectsAction.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/redux/reducers/canvasinfo.js
canvas_modules/common-canvas/src/object-model/redux/reducers/comments.js
canvas_modules/common-canvas/src/object-model/redux/reducers/externalpipelineflows.js
canvas_modules/common-canvas/src/object-model/redux/reducers/links.js
canvas_modules/common-canvas/src/object-model/redux/reducers/nodes.js
canvas_modules/common-canvas/webpack.config.js
canvas_modules/harness/cypress/integration/canvas/supernode-external.js
canvas_modules/harness/cypress/integration/canvas/supernode.js
canvas_modules/harness/src/client/App.js
scripts/publish_modules.sh

#786 Support deconstruction of a supernode

---

canvas_modules/common-canvas/src/command-actions/deconstructSuperNodeAction.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js

#794 Errors deconstructing supernode in allTypesCanvas.json

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-comments.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-nodes.js

#798 Overhaul link drawing code

---

canvas_modules/common-canvas/src/command-actions/createSuperNodeAction.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js

#800 Console errors creating a supernode in BigCanvas

---

canvas_modules/common-canvas/__tests__/common-properties/controls/numberfield-test.js
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss
canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx
canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.scss

Fixes #802 
Spinner control -
Numberfield control -
it.
(d) I …

#802 Number generator button next to numeric control

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/integration/canvas/supernode.js
canvas_modules/harness/cypress/support/canvas/object-model-cmds.js

#808 Nodes not appearing when added to full-page display of a sub-flow

---

canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2-canvas.jsx

#818 Tip handler error in console wtih explain 2 sample app

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#828 Improve drag behavior with large number of nodes

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/pipeline-in-handler.js
canvas_modules/common-canvas/src/object-model/pipeline-out-handler.js
canvas_modules/common-canvas/src/object-model/redux/canvas-store.js
canvas_modules/common-canvas/src/object-model/schemas-utils/upgrade-palette.js

#840 Clone data using cloneDeep

---

canvas_modules/common-canvas/src/palette/palette.scss

#779 Category names wrapped into second line

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js

#847 Refactor link creation code to improve perfomance

---

scripts/publish_modules.sh

#856 Fix build messages to use Elyra Canvas instad of common canvas

---

canvas_modules/common-canvas/src/command-actions/deleteObjectsAction.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/redux/reducers/canvasinfo.js
canvas_modules/common-canvas/src/object-model/redux/reducers/comments.js
canvas_modules/common-canvas/src/object-model/redux/reducers/externalpipelineflows.js
canvas_modules/common-canvas/src/object-model/redux/reducers/links.js
canvas_modules/common-canvas/src/object-model/redux/reducers/nodes.js
canvas_modules/common-canvas/src/object-model/redux/reducers/selectioninfo.js

#861 Deleting nodes, links in rapid succession crashes Canvas

---

canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx

#865 Palette search text not appearing highlighted in node descriptions

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/client/components/custom-canvases/logic/logic-canvas.jsx

#871 Error in console after dragging guide image near origin of line

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#875 Context menu remains displayed while dragging

---

canvas_modules/common-canvas/src/common-properties/properties-main/properties-main-widths.scss
canvas_modules/harness/cypress/integration/canvas/toolbar.js

#877 Aligned Properties Panel Widths to Carbon standard

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/integration/canvas/selection-region.js
canvas_modules/harness/cypress/support/canvas/operation-cmds.js

#883 Region select behaves differently for links and nodes

---

canvas_modules/common-canvas/__tests__/_utils_/common-canvas-utils.js
canvas_modules/common-canvas/__tests__/common-canvas/common-canvas-test.js
canvas_modules/common-canvas/__tests__/common-canvas/save-to-palette-test.js
canvas_modules/common-canvas/__tests__/common-canvas/supernode-test.js
canvas_modules/common-canvas/__tests__/context-menu/common-context-menu-test.js
canvas_modules/common-canvas/__tests__/notification-panel/notification-panel-test.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

Testing bottom panel right pannel

---

canvas_modules/common-canvas/src/common-properties/panels/control/control.jsx
canvas_modules/common-canvas/src/common-properties/panels/control/control.scss

#892 Removed padding for empty control group

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/action_paramDef.json
canvas_modules/common-canvas/src/common-properties/actions/image/image.jsx
canvas_modules/harness/cypress/integration/properties/actions.js
canvas_modules/harness/cypress/support/properties/properties-cmds.js
canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js
canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json

#898 Configurable action image tooltip direction

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/action_paramDef.json
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-properties/actions/image/image.jsx
canvas_modules/harness/cypress/integration/properties/actions.js
canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json

#898 Replace "tooltipDirection" with "tooltip_direction"

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/constants/canvas-constants.js
canvas_modules/common-canvas/src/common-properties/constants/constants.js

#905 Commonjs output is missing expected exported constant

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/harness/cypress/integration/canvas/config-enable-editing-actions.js

#920 Add ability to prevent creation of nodes

---

canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/custom-canvases/read-only/detachedCanvas.json
canvas_modules/harness/src/client/components/custom-canvases/read-only/detachedPalette.json
canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.jsx
canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.scss
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/constants.js
canvas_modules/harness/src/styles/index.scss

#928 Add a sample application to show read-only behaviors

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/common-canvas/src/palette/palette-content-list.jsx
canvas_modules/common-canvas/src/palette/palette-dialog-content-grid-node.jsx
canvas_modules/common-canvas/src/palette/palette-dialog-content-grid.jsx
canvas_modules/common-canvas/src/palette/palette-dialog-content.jsx
canvas_modules/common-canvas/src/palette/palette-dialog.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-content-filtered-list.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-content.jsx
canvas_modules/common-canvas/src/palette/palette-flyout.jsx
canvas_modules/common-canvas/src/palette/palette.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain/explain-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain/explainCanvas.json
canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.jsx
canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.scss

#932 Minor read-only canvas alterations

---

canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/harness/cypress/integration/canvas/tips.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/src/client/App.js

#937 When text is used in toolbar button don't show tooltip

---

canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx
canvas_modules/harness/package.json

#943 Use esm import for react-virtualized table

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/rollup.config.js
scripts/publish_modules.sh

#945 Fix Tree shaking in esm bundle

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js
canvas_modules/common-canvas/__tests__/test_resources/palettes/test-missing-fields.json
canvas_modules/common-canvas/src/palette/palette-flyout-utils.js

#947 Debug palette search input

---

canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/redux/canvas-store.js

#949 Opening right flyout with many nodes in canvas is slow

---

canvas_modules/harness/cypress/integration/canvas/node-insert-in-link.js

Test drag node over link

---

canvas_modules/common-canvas/__tests__/common-properties/controls/timestamp-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/timestamp_paramDef.json
canvas_modules/common-canvas/src/common-properties/constants/form-constants.js
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/harness/test_resources/parameterDefs/timestamp_paramDef.json

#961 Timestamp data type showing raw value instead of formated value

---

.github/workflows/build.yml
.github/workflows/publish.yml
canvas_modules/harness/README.md
canvas_modules/harness/package.json

#964 Update test harness and build to node 14

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-pipeline.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-nodes.js

#965 Copy and paste lead to performance issues

---

canvas_modules/common-canvas/__tests__/common-properties/components/table-buttons-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumns-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js
canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.jsx
canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.scss
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.scss
canvas_modules/common-canvas/src/common-properties/components/table-buttons/table-buttons.jsx
canvas_modules/common-canvas/src/common-properties/components/table-buttons/table-buttons.scss
canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.scss
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.scss
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.scss
canvas_modules/common-canvas/src/common-properties/controls/selectcolumns/selectcolumns.scss
canvas_modules/common-canvas/src/common-properties/controls/someofselect/someofselect.scss
canvas_modules/common-canvas/src/common-properties/panels/sub-panel/cell.jsx
canvas_modules/common-canvas/src/common-properties/panels/sub-panel/sub-panel.scss
canvas_modules/harness/cypress/integration/properties/structure-list-editor-table-control.js
canvas_modules/harness/cypress/integration/properties/structure-table-control.js

#967 Fix table button spacing and styling

---

canvas_modules/common-canvas/src/color-picker/color-picker-panel.jsx
canvas_modules/common-canvas/src/command-actions/colorSelectedObjectsAction.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/object-model/redux/reducers/comments.js
canvas_modules/harness/cypress/integration/canvas/comment.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/test_resources/diagrams/commentNewColorsCanvas.json

#975 Make default comment white-0

---

canvas_modules/common-canvas/__tests__/object-model/object-model-redux-test.js
canvas_modules/common-canvas/src/command-actions/pasteAction.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/redux/reducers/canvasinfo.js
canvas_modules/common-canvas/src/object-model/redux/reducers/comments.js
canvas_modules/common-canvas/src/object-model/redux/reducers/externalpipelineflows.js
canvas_modules/common-canvas/src/object-model/redux/reducers/links.js
canvas_modules/common-canvas/src/object-model/redux/reducers/selectioninfo.js

#965 Copy and paste lead to performance issues(part 2)

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/common-canvas/src/palette/palette-dialog-content-grid-node.jsx

#990 Drag and drop from palette leads to performance issues

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx

#992 Code cleanup (part 2)

---

scripts/publish_modules.sh

Change minor to patch

---

canvas_modules/common-canvas/locales/common-canvas/locales/en.json
canvas_modules/common-canvas/locales/common-canvas/locales/eo.json
canvas_modules/common-canvas/src/common-canvas/cc-toolbar.jsx

#1012 Undo/redo tooltips show multiple suggestions

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/expressionControl_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx
canvas_modules/harness/test_resources/parameterDefs/expressionControl_paramDef.json

#1017 Support strings in expression builder min and max range

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx

#1022 Save expression on panel value when clicked on table row

---

canvas_modules/common-canvas/__tests__/common-properties/components/control-item-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/action_paramDef.json
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/checkbox_paramDef.json
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/controls/checkbox/checkbox.jsx
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/common-canvas/src/common-properties/util/L10nProvider.js
canvas_modules/common-canvas/src/tooltip/tooltip.jsx
canvas_modules/common-canvas/src/tooltip/tooltip.scss
canvas_modules/harness/src/client/App.js
canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json
canvas_modules/harness/test_resources/parameterDefs/checkbox_paramDef.json

#1000 Add a link in properties tooltip

---

canvas_modules/common-canvas/__tests__/_utils_/table-utils.js
canvas_modules/common-canvas/__tests__/common-properties/components/fieldpicker-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/someofselect-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structureeditor-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js
canvas_modules/common-canvas/__tests__/common-properties/defaults-test.js
canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.jsx
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx

#1015 Select/deselect multiple rows in table using shift key

---

canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx

#1026 Removed empty flexible table header

---

canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumns-test.js
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/someofselect/someofselect.jsx

#1030 Flexible table has default height of 5.5 rows

---

canvas_modules/common-canvas/__tests__/command-stack/command-stack.js
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/command-stack/command-stack.js
canvas_modules/common-canvas/src/command-stack/internal-stack.js

#1038 Replace immutable-undo with either a new module or recreate in code

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/harness/cypress/integration/canvas/zoom.js

#1042 Saved zoom not retrieved correctly from Local Storage

---

canvas_modules/common-canvas/__tests__/common-properties/actions/button-action-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/action_paramDef.json
canvas_modules/common-canvas/src/common-properties/actions/button/button.jsx
canvas_modules/common-canvas/src/common-properties/actions/button/button.scss
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/form/ActionInfo.js
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json

#1040 Support kind and size options in action buttons

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.scss

#1044 Draggable border in script panel is too thick

---

scripts/publish_modules.sh

Create patch release

---

canvas_modules/common-canvas/__tests__/test_resources/palettes/expected-add-supernode.json
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/pipeline-in-handler.js
canvas_modules/harness/test_resources/palettes/supernodePalette.json

#1049 Change pipeline_data field from app_data to app_data.ui_data

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-builder.jsx

#1054 Expression editor is focused after adding field and operation

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx

 #1062 Expression editor is editable after clicking validate

---

canvas_modules/harness/src/client/components/custom-canvases/flows/flowsCanvas.json

#1066 Flows canvas sample app - nodes in flow position incorrectly

---

.github/workflows/build.yml
canvas_modules/harness/build.sh
canvas_modules/harness/functional_test.sh

#1071 Fix cypress error in build

---

canvas_modules/common-canvas/__tests__/common-properties/panels/action-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/action_paramDef.json
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/panelConditions_paramDef.json
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/panels/action-panel/action-panel.jsx
canvas_modules/common-canvas/src/common-properties/panels/action-panel/action-panel.scss
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/constants/properties-documentation-constants.js
canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json
canvas_modules/harness/test_resources/parameterDefs/panelConditions_paramDef.json

Fixes #1083 
In `action_paramDef.json` - 
In `panelConditions_paramDef.json` -
person who certified (a), (b) or (c) and I have not …

#1083 Support label and description in actionPanel

---

.github/workflows/build.yml
CONTRIBUTING.md
README.md
canvas_modules/common-canvas/README.md
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/harness/src/client/components/common-properties-components.jsx
canvas_modules/harness/src/client/components/common-properties-conditions.jsx
canvas_modules/harness/src/client/components/ctrl/CustomEffectsCtrl.jsx
code-of-conduct.md
scripts/create_release.sh
scripts/publish_modules.sh
scripts/source_scan.sh

#1081 Rename master to main

---

canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/harness/cypress/support/canvas/palette-cmds.js

#1072 Implement accessibility for the new Accordion palette - Tidy up

---

canvas_modules/common-canvas/src/tooltip/tooltip.jsx

#1097 Fixed page freeze for multiple row tables having subpanels

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx

#1099 Error dropping nodes onto canvas in firefox

---

scripts/publish_modules.sh

Change build script patch to minor

---

canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.scss

#1104 Empty flexible table height

---

canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/tooltip/tooltip.jsx
canvas_modules/harness/src/client/App.js

#1107 Tooltips not displaying for JSX tools in toolbar

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js

 #1111 Added a config option filterHiddenControls in getPropertyValues() method

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#1115 Declare 'associative entities' as objects instead of arrays

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js

#1126 Palette test not setting up Palette object correctly

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js
canvas_modules/common-canvas/src/palette/palette-flyout-content-category.jsx
canvas_modules/common-canvas/src/palette/palette.scss

#1125 Remove icons from palette when category is closed

---

canvas_modules/common-canvas/src/command-actions/createSuperNodeAction.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/object-model/config-utils.js

#1142 On Supernode creation allow original port cardinality to be used

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx
canvas_modules/common-canvas/src/common-properties/controls/expression/expression.scss

Fixes #1162 
Light option enabled - 
Light option disabled - 
it.
(d) …

#1162 Show line numbers in code and expression controls

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.scss

#1168 Update CodeMirror CSS

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/checkboxset_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/checkboxset/checkboxset.scss
canvas_modules/harness/test_resources/parameterDefs/checkboxset_paramDef.json

fixes #1177 
caused by https://github.com/elyra-ai/canvas/commit/7c8165aa7885a5476d7709ccafdcd6f7ee79676a
person who certified …

#1177 Checkboxset long value labels alignment

---

canvas_modules/common-canvas/__tests__/common-properties/conditions/panel-conditions-test.js
canvas_modules/common-canvas/__tests__/common-properties/panels/text-test.js
canvas_modules/common-canvas/__tests__/common-properties/panels/twisty-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/panelConditions_paramDef.json
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/harness/package.json
canvas_modules/harness/test_resources/parameterDefs/panelConditions_paramDef.json

#1181 Allow primary panels to be hidden

---

canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.scss

#1194 Fix calculation syntax in common-properties

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/code_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/passwordfield/passwordfield.jsx
canvas_modules/common-canvas/src/common-properties/ui-conditions/ui-conditions-parser.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/ui-groups-parser.js
canvas_modules/harness/test_resources/parameterDefs/code_paramDef.json

#1201 Set controls in tearsheet panel

---

canvas_modules/common-canvas/src/context-menu/common-context-menu.jsx
canvas_modules/common-canvas/src/context-menu/context-menu-wrapper.jsx

#1199 Context menu should appear when ellipsis button clicked on Firefox

---

canvas_modules/common-canvas/__tests__/common-properties/controls/toggle-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/toggle_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/toggle/toggle.jsx
canvas_modules/common-canvas/src/common-properties/controls/toggle/toggle.scss
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/harness/test_resources/parameterDefs/toggle_paramDef.json

#1188 Labels are missing in both Warning and Error toggles

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-decs.js

#1205 Edit icon for link name translates very far away upon long name

---

canvas_modules/common-canvas/__tests__/common-properties/panels/tearsheet-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/code_paramDef.json
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/harness/test_resources/parameterDefs/code_paramDef.json

#1214 Fix Tearsheet to render on visibility condition

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/constants/canvas-constants.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/integration/canvas/drag.js
canvas_modules/harness/cypress/integration/canvas/undo-redo.js
canvas_modules/harness/cypress/integration/canvas/zoom.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/operation-cmds.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/constants.js

#1185 Implement recommended icon-display and mouse behaviors for canvas

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-decs.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js

#1225 Improve default settings for multi-line labels

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
scripts/publish_modules.sh

#1228 Zoom not working on Firefox

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-textarea.js
canvas_modules/harness/cypress/integration/canvas/comment.js

#1221 Completing comment edit should not remove selection state

---

canvas_modules/common-canvas/__tests__/toolbar/toolbar-test.js
canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-overflow-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.scss

#1249 Unwanted assistive text appearing in toolbar drop down

---

canvas_modules/common-canvas/__tests__/common-properties/controls/numberfield-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/common-properties/locales/eo.json
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx

#1197 Show error for invalid number in Numberfield and Spinner controls

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-decs.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/src/client/components/custom-canvases/stages-card-node/stages-card-node-canvas.jsx

#1262 Fix decoration label callback

---

canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-toggle/expression-toggle.jsx

fixes #1265 
Signed-off-by: Jesus Rocha <jesus.rocha@ibm.com>
it.
(d) …

1265 Expression tests cause locale error

---

canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js
canvas_modules/common-canvas/__tests__/test_resources/json/structuretable_propertyValues.json
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structuretable_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx
canvas_modules/harness/test_resources/parameterDefs/structuretable_paramDef.json

fixes #1246
Signed-off-by: Jesus Rocha <jesus.rocha@ibm.com>
it.
(d) …

#1246 Unable to set oneofselect in MSE when reusing previous selection

---

canvas_modules/harness/src/client/components/custom-canvases/explain/explain-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2-canvas.jsx

#1283 Minor chnages to sample apps

---

canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.scss

issue https://github.com/elyra-ai/canvas/issues/1278
it.
(d) I …

#1278 sticky primary tabs in tearsheet

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/src/client/components/custom-canvases/explain/explain-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/explain/explain.scss
canvas_modules/harness/src/client/components/custom-canvases/explain/explainCanvas.json

#1287 Allow class name to be specified in node layout properties

---

canvas_modules/common-canvas/__tests__/common-properties/panels/tearsheet-test.js
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.scss
canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.jsx
canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.scss
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx

#1278 Hide close button if footer buttons visible in tearsheet

---

canvas_modules/common-canvas/src/common-properties/controls/radioset/radioset.scss

Signed-off-by: nabik <nabil@nabil.com>
it. …

#1276 Handle spacing in common properties

---

canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.jsx
canvas_modules/harness/src/client/components/custom-canvases/read-only/readOnlyCanvas.json
canvas_modules/harness/src/client/components/custom-canvases/read-only/readOnlyPalette.json
canvas_modules/harness/src/client/components/custom-canvases/stages-card-node/stages-card-node-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages.scss

#1299 Fix detached links issues

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx

#1301 enableSnapToGridX/Y causing resize node issues possibly

---

canvas_modules/common-canvas/__tests__/common-properties/controls/expression-test.js
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx

#1307 Expression builder should only quote field if it contains special characters

---

canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.scss
canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.scss
canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.jsx
canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.scss

#1279 Display field-picker in stacked tearsheet

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-pipeline.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#1318 Remove unneeded code

---

canvas_modules/common-canvas/__tests__/toolbar/toolbar-test.js

Fixes : #1326 
Signed-off-by: nabik <nabil@nabil.com>
it.
(d) I …

#1326 Warning appearing running toolbar-test.js

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/src/common-properties/components/properties-modal/properties-modal.scss
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx
canvas_modules/common-canvas/src/common-properties/controls/list/list.jsx
canvas_modules/common-canvas/src/common-properties/controls/selectcolumns/selectcolumns.jsx
canvas_modules/common-canvas/src/common-properties/controls/someofselect/someofselect.jsx
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/form/Form.js
canvas_modules/common-canvas/src/common-properties/panels/sub-panel/sub-panel.scss
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/harness/test_resources/parameterDefs/subpanel_paramDef.json

tearsheet subpanel modals

---

canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel.jsx
canvas_modules/harness/src/client/constants/constants.js
canvas_modules/harness/src/styles/App.scss
canvas_modules/harness/src/styles/index.scss
canvas_modules/harness/src/styles/sidepanel.scss

#1330 Test harness - Hide side panel contents when panel is closed

---

canvas_modules/common-canvas/src/object-model/redux/canvas-store.js

#1335 Add additional checks for pipeline in getNonClonedSelectedObjs()

---

canvas_modules/common-canvas/__tests__/common-properties/utils/property-utils-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/convertValueDataTypes_paramDef.json
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/form/Form.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/common-canvas/src/common-properties/util/property-utils.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-properties.jsx
canvas_modules/harness/test_resources/parameterDefs/convertValueDataTypes_paramDef.json

#1342 config convert values

---

canvas_modules/common-canvas/__tests__/common-properties/conditions/panel-conditions-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/datefield-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/expression-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/radioset-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/readonlytable-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/spinner-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structureeditor-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/timefield-test.js
canvas_modules/common-canvas/__tests__/common-properties/panels/columnselection-test.js
canvas_modules/common-canvas/__tests__/common-properties/panels/tearsheet-test.js
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/controls.scss

#1346 Do not render hidden controls

---

canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx
canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.scss

Signed-off-by: Matt Howard <mwhoward@us.ibm.com>
it.
(d) I understand …

#1352 Update styling of properties error panel

---

canvas_modules/common-canvas/src/common-properties/controls/control-factory.js

#1350 Unable to open subpanel of structureeditor in tearsheet

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-pipeline.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/integration/canvas/zoom.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-api.jsx
canvas_modules/harness/src/client/constants/constants.js

#1360 Enable getZoomToReveal to work with links

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#1356 ClickActionHandler not being called with Mouse Interaction type

---

canvas_modules/common-canvas/__tests__/notification-panel/notification-panel-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/notification-panel/locales/en.json
canvas_modules/common-canvas/locales/notification-panel/locales/eo.json
canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss

Signed-off-by: Sara Akhtar <sara.akhtar@ibm.com>
Fixes #1368. 
it. …

#1368 Align Close Icon With Carbon

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/readonlyTable_paramDef.json
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss
canvas_modules/harness/test_resources/parameterDefs/readonlyTable_paramDef.json

Fixes #1372
Signed-off-by: Neha-Gokhale <Neha.Gokhale@ibm.com>
it. …

#1372 Add a line break when on panel description contains \n

---

canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/harness/src/client/components/ctrl/CustomEffectsCtrl.jsx
canvas_modules/harness/src/client/components/custom-panels/RandomEffectsPanel.js

#1375 Fix glmm example in properties

---

canvas_modules/common-canvas/__tests__/palette/palette-test.js

1377 Warnings showing up in jests tests

---

canvas_modules/common-canvas/__tests__/common-properties/components/control-item-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/multiselect-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/oneofselect-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumn-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/selectschema-test.js
canvas_modules/common-canvas/__tests__/common-properties/form/form-test.js
canvas_modules/common-canvas/__tests__/test_resources/json/form-actions-test.json
canvas_modules/common-canvas/__tests__/test_resources/json/form-editstyle-test.json
canvas_modules/common-canvas/__tests__/test_resources/json/form-structure-test.json
canvas_modules/common-canvas/__tests__/test_resources/json/form-structure2-test.json
canvas_modules/common-canvas/__tests__/test_resources/json/form-test-condition.json
canvas_modules/common-canvas/__tests__/test_resources/json/form-test.json
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/form/ControlInfo.js
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/common-canvas/src/common-properties/form/ParameterInfo.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-properties.jsx

Fixes #1379 
Added toggle in harness for testing -
it.
(d) I …

 #1379 Added a config option for required/optional label indicator

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

Node port icon still displayed after outputs array is set to undefined

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/cc-central-items.jsx
canvas_modules/common-canvas/src/common-canvas/cc-top-panel.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/redux/canvas-store.js
canvas_modules/common-canvas/src/object-model/redux/reducers/toppanel.js
canvas_modules/harness/cypress/integration/canvas/top-panel.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel-canvas.jsx

#1385 Enhancement request: Add top panel option

---

canvas_modules/common-canvas/__tests__/common-properties/components/fieldpicker-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/list-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumns-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js
canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx

Fixes #1389 
Before -
After -
it.
(d) I understand and agree that …

#1389 Accessibility: Fixed violation in properties table

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/harness/assets/images/custom-canvases/stages/decorations/tri-down.svg
canvas_modules/harness/assets/images/custom-canvases/stages/decorations/tri-up.svg
canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages-card-node/stages-card-node-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx

#1394 Reverse change to common-canvas scss

---

canvas_modules/common-canvas/src/notification-panel/notification-panel.scss

Fix CSS for Close Button in Notification Panel

---

scripts/publish_modules.sh

Change to build patch

---

canvas_modules/common-canvas/__tests__/common-properties/actions/button-action-test.js
canvas_modules/common-canvas/__tests__/common-properties/actions/image-action-test.js
canvas_modules/common-canvas/__tests__/common-properties/components/control-item-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/checkboxset-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/expression-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/radioset-test.js
canvas_modules/common-canvas/__tests__/common-properties/panels/text-test.js
canvas_modules/common-canvas/src/common-properties/actions/button/button.jsx
canvas_modules/common-canvas/src/common-properties/actions/image/image.jsx
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.jsx
canvas_modules/common-canvas/src/common-properties/components/truncated-content-tooltip/truncated-content-tooltip.jsx
canvas_modules/common-canvas/src/common-properties/components/validation-message/validation-message.jsx
canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx
canvas_modules/common-canvas/src/common-properties/controls/checkbox/checkbox.jsx
canvas_modules/common-canvas/src/common-properties/controls/checkboxset/checkboxset.jsx
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-operator.jsx
canvas_modules/common-canvas/src/common-properties/controls/radioset/radioset.jsx
canvas_modules/common-canvas/src/common-properties/controls/textarea/textarea.jsx
canvas_modules/common-canvas/src/common-properties/controls/textfield/textfield.jsx
canvas_modules/common-canvas/src/common-properties/panels/sub-panel/cell.jsx
canvas_modules/common-canvas/src/common-properties/panels/summary/summary.jsx
canvas_modules/common-canvas/src/common-properties/util/property-utils.js
canvas_modules/common-canvas/src/tooltip/tooltip.jsx
canvas_modules/common-canvas/src/tooltip/tooltip.scss
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
scripts/publish_modules.sh

Fixes: #1402 
Followed same pattern as [carbon tooltip](https://v10.carbondesignsystem.com/components/tooltip/code/). 
- For toolbar - Added `aria-labelledby` attribute to the `tooltip-trigger` element.
- For common-properties tooltips - Added `aria-labelledby, aria-expanded, aria-controls` attributes to the `tooltip-trigger` element. 
Follwing [ARIA example](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role#examples) -
Added `role="tooltip", id` attributes to actual tooltip content having `className="common-canvas-tooltip"`.
**Before -**
**After -**
have the right to submit it under the Apache …

#1402 Accessibility: Fixed Tooltip element's role 'none' is not a widget role

---

canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss

Fixes #1416 
**Before -**
**After removing spacing -**
it.
(d) I …

#1416 Removed control label spacing

---

canvas_modules/common-canvas/__tests__/common-properties/utils/property-utils-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/convertValueDataTypes_paramDef.json
canvas_modules/common-canvas/src/common-properties/form/Form.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/common-canvas/src/common-properties/util/property-utils.js
canvas_modules/harness/test_resources/parameterDefs/convertValueDataTypes_paramDef.json

#1414 Extend 'convertValueDataTypes' support to 'setPropertyValues'

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#1424 Unable to single left-click and select node in read-only mode

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#1410  User request: Add Show/Hide Comments (Part 2)

---

canvas_modules/common-canvas/__tests__/common-properties/utils/property-utils-test.js
canvas_modules/common-canvas/src/common-properties/util/property-utils.js
scripts/publish_modules.sh

#1428 Fix error when converting current parameters if control is not defined

---

canvas_modules/common-canvas/__tests__/common-properties/components/truncated-content-tooltip-test.js
canvas_modules/common-canvas/__tests__/common-properties/components/truncated-content-tooltip.js
canvas_modules/common-canvas/src/common-properties/components/truncated-content-tooltip/truncated-content-tooltip.jsx

#1430 Fix tooltip error without content

---

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/datepicker_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/datepicker/datepicker.scss
canvas_modules/harness/src/client/constants/properties-documentation-constants.js
canvas_modules/harness/test_resources/parameterDefs/datepicker_paramDef.json

#1434 Calendar icon is misaligned in datepicker with long helper text

---

canvas_modules/common-canvas/src/tooltip/tooltip.jsx
canvas_modules/harness/src/client/App.js

Fixes #1440 
Before - 
After - 
it.
(d) I understand and agree that …

#1440 Accessibility: Fixed 'aria-labelledby' are not valid for the element <div> with implicit ARIA role 'generic'

---

canvas_modules/common-canvas/src/common-properties/controls/passwordfield/passwordfield.jsx

#1447 Fixed issue page refresh after clicking 'enter/return' key in password control

---

canvas_modules/common-canvas/src/common-properties/ui-conditions/ui-conditions.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/custom/condition-ops/customFilterDuplicates.js
canvas_modules/harness/src/client/custom/condition-ops/customFilterKeys.js
canvas_modules/harness/test_resources/parameterDefs/merge_paramDef.json

#1455 Support custom filter conditions in properties

---

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js
canvas_modules/common-canvas/__tests__/common-properties/components/main-editor-proprties-button-test.js
canvas_modules/common-canvas/__tests__/common-properties/conditions/alerts-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/datefield-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/datepicker-range-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/datepicker-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/textfield-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/timefield-test.js
canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/__tests__/flow-validation/flow-validation-test.js
canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/locales/common-properties/locales/eo.json

#1461 Update required error message in properties

---

scripts/publish_modules.sh

Change patch build to minor

---

canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.scss

Closes #1464 
https://user-images.githubusercontent.com/25124000/235262189-60be4f20-b532-4381-a13a-e04187bd7135.mov
person who …

#1464 Fixed issue sort icon outside table header

---

canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.scss
canvas_modules/harness/src/client/components/sidepanel/properties/sidepanel-properties.jsx

#1468 Datepicker controls are in the wrong color within a Tearsheet

---

canvas_modules/common-canvas/__tests__/common-properties/actions/button-action-test.js
canvas_modules/common-canvas/__tests__/common-properties/actions/image-action-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/action_paramDef.json
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-properties/actions/button/button.jsx
canvas_modules/common-canvas/src/common-properties/actions/image/image.jsx
canvas_modules/common-canvas/src/common-properties/form/ActionInfo.js
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json

Fixes #1466 
Custom classes for action button and image - 
it.
(d) I …

#1466 Support custom class for action button and image

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-external.js
canvas_modules/common-canvas/src/object-model/pipeline-out-handler.js
canvas_modules/harness/cypress/integration/canvas/decorators.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#1470 Enable JSX decorations

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#1474 Canvas crash - Cannot read properties of undefined (reading x1)

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js
canvas_modules/common-canvas/__tests__/test_resources/palettes/image-test-palette.json
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/redux/canvas-store.js
canvas_modules/common-canvas/src/object-model/redux/reducers/categories.js
canvas_modules/common-canvas/src/object-model/redux/reducers/palette.js
canvas_modules/common-canvas/src/palette/palette-flyout-content-category.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-content.jsx

#1478 Open each category in palette by default at start

---

canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx

#1485 Fixed when rows=-1 in tearsheet the max height isn't calculated correctly

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js

#1487 Show previous value in PropertyListener UPDATE_PROPERTY action

---

canvas_modules/common-canvas/src/common-canvas/cc-toolbar.jsx

[Issue: 1489
](https://github.com/elyra-ai/canvas/issues/1489)
it. …

#1489 notificationConfig is ignoring the enable attribute

---

canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx
canvas_modules/harness/test_resources/forms/type.json

Fixes #1495 
https://github.com/elyra-ai/canvas/assets/25124000/d3d05c6e-9be2-42f8-882c-979425ce8901
person who certified (a), (b) …

#1495 Fixed resizing column causes table size to lock when followed by changing editorSize

---

canvas_modules/common-canvas/__tests__/common-properties/operators/greaterThan-test.js
canvas_modules/common-canvas/__tests__/common-properties/operators/isEmpty-test.js
canvas_modules/common-canvas/__tests__/common-properties/operators/isNotEmpty-test.js
canvas_modules/common-canvas/__tests__/common-properties/operators/lessThan-test.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/condition-ops/greaterThan.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/condition-ops/isDateTime.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/condition-ops/isEmpty.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/condition-ops/isNotEmpty.js
canvas_modules/common-canvas/src/common-properties/ui-conditions/condition-ops/lessThan.js
scripts/publish_modules.sh

#1497 Add additional checks in properties conditions for the control in cases where they are not defined

---

canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.scss

#1500 Toolbar overflow menu does not expand for longer text

---

canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/custom-canvases/flows/flows-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages-card-node/stages-card-node-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx

#1504 Context toolbar not appearing for selected canvas

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js

#1520 Horizontal nodes with input ports flashes on click

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/config-utils.js

#1522 Node icons are flashing when canvas config is altered

---

canvas_modules/common-canvas/src/color-picker/color-picker.jsx
canvas_modules/common-canvas/src/command-actions/colorSelectedObjectsAction.js

#1527 Undo comment color token changes

---

scripts/publish_modules.sh

Change patch to minor release

---

canvas_modules/common-canvas/src/common-canvas/cc-context-toolbar.jsx
scripts/publish_modules.sh

#1530 Node context toolbar broken in Firefox ESR

---

canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx

Closes #1543 
https://github.com/elyra-ai/canvas/assets/25124000/7ff589e4-434d-40ee-aa34-2aeaec583bb9 …

#1543 Fixed properties editor crashes when using numberfield cell condition

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/client/App.js
scripts/publish_modules.sh

#1549 Provide field to differentiate different updateLink gestures

---

canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx

#1553 Duplicate ID in toolbar causing accessibility errors

---

canvas_modules/common-canvas/src/common-canvas/cc-central-items.jsx
canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/cc-right-flyout.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss

#1557 Top and bottom panel don't interact with the canvas area correctly

---

canvas_modules/common-canvas/package.json

#1559 Consider adding React 17 support to @elyra/canvas

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-pipeline.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/common-canvas/src/object-model/redux/reducers/canvasinfo.js
canvas_modules/common-canvas/src/object-model/redux/reducers/links.js

#1569 Add a setLinks method to canvas controller

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#1580 Drag behavior incorrectly removed with enableEditingAction: false

---

canvas_modules/common-canvas/src/object-model/object-model.js

#1582 Resize height and width used even when isResized is false

---

canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.jsx
canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.scss
canvas_modules/harness/src/client/components/custom-canvases/read-only/readOnlyCanvas.json

#1584 Remove stroke from read-only nodes

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx

#1590 Contents div should be opened in appropriate order

---

canvas_modules/common-canvas/src/palette/palette.scss

#1592 Palette items are not left aligned

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#1596 Use separate function to apply listeners to link handles

---

canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx

#1613 Allow individual palette nodes to be disabled (for double-click)

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-external.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-zoom.js

#1615 Refactor zoom code into a utility file (for consistency)

---

canvas_modules/common-canvas/locales/common-canvas/locales/en.json
canvas_modules/common-canvas/locales/common-canvas/locales/eo.json
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/common-canvas/constants/canvas-constants.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js

#1129 Externalize string 'Return to previous flow'

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-objects.js
canvas_modules/harness/cypress/e2e/canvas/context-menu.cy.js
canvas_modules/harness/cypress/e2e/canvas/drag.cy.js
canvas_modules/harness/cypress/e2e/canvas/supernode.cy.js
canvas_modules/harness/cypress/e2e/canvas/toolbar.cy.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#1624 Enable skipped tests to run in Cypress

---

canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss

#1627 Cannot edit nodes below the notification panel

---

canvas_modules/common-canvas/locales/common-canvas/locales/de.json
canvas_modules/common-canvas/locales/common-canvas/locales/es.json
canvas_modules/common-canvas/locales/common-canvas/locales/fr.json
canvas_modules/common-canvas/locales/common-canvas/locales/it.json
canvas_modules/common-canvas/locales/common-canvas/locales/ja.json
canvas_modules/common-canvas/locales/common-canvas/locales/ko.json
canvas_modules/common-canvas/locales/common-canvas/locales/pt-br.json
canvas_modules/common-canvas/locales/common-canvas/locales/sv.json
canvas_modules/common-canvas/locales/common-canvas/locales/zh-CN.json
canvas_modules/common-canvas/locales/common-canvas/locales/zh-TW.json

#1631 updated translations

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/package.json
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel/canvas/sidepanel-canvas.jsx

#1638 Prototype creation of a PDF containing an image of the canvas.

---

canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.scss
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx

#1636 Searchbar in FlexibleTable is not honoring the light prop

---

canvas_modules/common-canvas/__tests__/common-properties/components/flexibletable-test.js
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx

#1655 Readjust FlexibleTable height when number of rows changes

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js

#1657 setDefaultValues config option should call propertyListener() once

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller-menu-utils.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/constants/canvas-constants.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/redux/reducers/canvasinfo.js
canvas_modules/common-canvas/src/object-model/redux/reducers/comments.js
canvas_modules/common-canvas/src/object-model/redux/reducers/links.js
canvas_modules/common-canvas/src/object-model/redux/reducers/nodes.js
canvas_modules/harness/src/styles/canvas-customization.scss
scripts/publish_modules.sh

#1659 Highlight branch feature to support dark theme or custom css

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
scripts/publish_modules.sh

#1666 Fixed bug setDefaultValues option clears all the existing properties

---

canvas_modules/common-canvas/locales/common-properties/locales/de.json
canvas_modules/common-canvas/locales/common-properties/locales/es.json
canvas_modules/common-canvas/locales/common-properties/locales/fr.json
canvas_modules/common-canvas/locales/common-properties/locales/it.json
canvas_modules/common-canvas/locales/common-properties/locales/ja.json
canvas_modules/common-canvas/locales/common-properties/locales/ko.json
canvas_modules/common-canvas/locales/common-properties/locales/pt-br.json
canvas_modules/common-canvas/locales/common-properties/locales/sv.json
canvas_modules/common-canvas/locales/common-properties/locales/zh-CN.json
canvas_modules/common-canvas/locales/common-properties/locales/zh-TW.json

Issue #: https://github.com/elyra-ai/canvas/issues/1676
it.
(d) I …

#1676 New Translation Update

---

canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/harness/src/client/components/common-properties-components.jsx
canvas_modules/harness/src/client/components/common-properties-conditions.jsx
canvas_modules/harness/src/client/constants/properties-documentation-constants.js

#1684 : Add Slider Control Documentation in Common Properties

---

canvas_modules/common-canvas/src/common-properties/components/wide-flyout/wide-flyout.scss

#1682 [Dark mode] Text Analysis and other nodes - overlay color

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel/properties/sidepanel-properties-param-def.json
canvas_modules/harness/src/client/components/sidepanel/properties/sidepanel-properties.jsx

Add set active tab method in Common Properties

---

canvas_modules/common-canvas/src/object-model/redux/canvas-store.js

#1695 Elyra/canvas failed with error while rendered on Node.js

---

canvas_modules/common-canvas/src/toolbar/toolbar.scss

#1709 Animate the opening of toolbar sub-areas

---

canvas_modules/common-canvas/rollup.config.js
canvas_modules/common-canvas/src/common-properties/controls/expression/languages/python-hint.js
canvas_modules/common-canvas/src/common-properties/controls/expression/languages/r-hint.js
canvas_modules/common-canvas/src/common-properties/index.js
canvas_modules/common-canvas/src/index.js

#1715 Export getPythonHints and clem from common-properties

---

canvas_modules/common-canvas/__tests__/common-canvas/common-canvas-test.js
canvas_modules/common-canvas/__tests__/common-canvas/common-canvas-toolbar-test.js
canvas_modules/common-canvas/__tests__/notification-panel/notification-panel-test.js
canvas_modules/common-canvas/src/color-picker/color-picker.jsx
canvas_modules/common-canvas/src/common-canvas/cc-central-items.jsx
canvas_modules/common-canvas/src/common-canvas/cc-toolbar.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss
canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-button-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-divider-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-overflow-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-sub-menu-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-sub-menu.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-sub-panel.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-sub-utils.js
canvas_modules/common-canvas/src/toolbar/toolbar.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.scss
canvas_modules/harness/cypress/e2e/canvas/notifications.cy.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/app-x-settings-panel.jsx

#1717 Accessibility: Notification panel should be enabled for keyboard navigation

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/notification-panel/notification-panel.scss
canvas_modules/common-canvas/src/palette/palette.scss
canvas_modules/common-canvas/src/toolbar/toolbar.scss

#1723 Some dark mode styling issues

---

canvas_modules/common-canvas/src/common-properties/controls/checkbox/checkbox.scss

#1732 Fix Common Properties Checkbox Information Icon alignment for long text.

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss

#1735 Comment box - Higher text contrast

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/src/styles/canvas-customization.scss

#1739 Tooltip should change when moving cursor from decoration to node

---

canvas_modules/common-canvas/src/toolbar/toolbar-overflow-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.jsx
canvas_modules/harness/src/client/app-x-settings-panel.jsx

#1742 Overflow menu is not closed when canvas width is increased

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-nodes.js
canvas_modules/common-canvas/src/object-model/config-utils.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/common-canvas/src/object-model/object-model-utils.js
canvas_modules/harness/cypress/e2e/canvas/supernode.cy.js

#1750 Setting input port positions for nodes with multiple inputs

---

canvas_modules/common-canvas/src/icons/icon.scss

#1754 Tooltip information icon should use -02 color

---

README.md
canvas_modules/harness/package.json

Fixes : #1758
Fix Typo in mkdocs instructions in Readme and add comment to remove NODE_OPTIONS in test harness package.json. …

#1758 : Typo in Readme

---

README.md
canvas_modules/common-canvas/package.json

Fixes #1761 
PR for `v12.x` branch
it. …

#1761 Add Elyra documentation link in readme and npm (#1762)

---

.github/workflows/build.yml
.github/workflows/publish.yml
README.md
canvas_modules/harness/README.md
canvas_modules/harness/package.json

Revert "V12.x"

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-objects.js

#1784 Two size node events being redone as one

---

canvas_modules/common-canvas/src/toolbar/toolbar.scss
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/app-x-settings-panel.jsx

#1782 Toolbar CSS styles are applied in sub-panels

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

Cnavas controller - Fix comment

---

.github/workflows/build.yml
.github/workflows/publish.yml
README.md
canvas_modules/harness/README.md
canvas_modules/harness/package.json

This reverts commit f5b067f744a9adaa82d40b60173b66220b0f5807.
it.
(d) …

Revert "Revert "V12.x" (#1793)"

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-objects.js

#1784 Two size node events being redone as one (#1785)

---

canvas_modules/common-canvas/src/toolbar/toolbar.jsx

#1811 First right-side toolbar item is displayed in overflow menu

---

canvas_modules/common-canvas/src/command-stack/command-stack.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/cc-toolbar.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/multi-undo-panel.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx

#1815 Create a prototype of multiple-undo capability

---

canvas_modules/common-canvas/src/toolbar/toolbar.scss
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/app-x-settings-panel.jsx

Css styles for toolbar v12

---

canvas_modules/common-canvas/src/command-stack/command-stack.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/cc-toolbar.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/multi-undo-panel.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx

#1815 Create a prototype of multiple-undo capability (#1816)

---

docs/pages/01-install/index.md

#1821 Update styling documentation for Carbon 11

---

canvas_modules/common-canvas/locales/common-properties/locales/de.json
canvas_modules/common-canvas/locales/common-properties/locales/es.json
canvas_modules/common-canvas/locales/common-properties/locales/fr.json
canvas_modules/common-canvas/locales/common-properties/locales/it.json
canvas_modules/common-canvas/locales/common-properties/locales/ja.json
canvas_modules/common-canvas/locales/common-properties/locales/ko.json
canvas_modules/common-canvas/locales/common-properties/locales/pt-br.json
canvas_modules/common-canvas/locales/common-properties/locales/sv.json
canvas_modules/common-canvas/locales/common-properties/locales/zh-CN.json
canvas_modules/common-canvas/locales/common-properties/locales/zh-TW.json

Issue: https://github.com/elyra-ai/canvas/issues/1824 
it.
(d) I …

#1824 Delta Translations

---

canvas_modules/common-canvas/src/toolbar/toolbar.scss

#1832 Background color of selected toolbar icons has been lost

---

canvas_modules/common-canvas/src/common-canvas/cc-context-toolbar.jsx

#1826 Context toolbar is partly off the screen (#1827)

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#1829 editActionHandler not called with multi-undo prototype (#1830)

---

canvas_modules/common-canvas/src/toolbar/toolbar.scss

#1832 Background color of selected toolbar icons has been lost (#1833)

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-zoom.js

#1846 Enable zoomTo function to execute with animation

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-zoom.js

#1846 Enable zoomTo function to execute with animation (#1847)

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#1851 Tiny app not working

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#1851 Tiny app not working (#1852)

---

docs/pages/index.md

#1862 Fix docs - home page not coming up when running on github.io

---

canvas_modules/common-canvas/__tests__/toolbar/toolbar-test.js

#1872 Use React Testing Library for Toolbar Tests

---

docs/pages/03.03-callbacks.md
docs/pages/03.03.01-context-menu-handler.md
docs/pages/index.md

More docs changes

---

docs/pages/03.03-callbacks.md
docs/pages/03.03.01-context-menu-handler.md
docs/pages/index.md

More docs changes (#1871)

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-external.js

1878 Don't createRoot every time node data changes in SvgCanvasExternal

---

canvas_modules/common-canvas/__tests__/common-properties/controls/datefield-test.js
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/controls/datefield/datefield.jsx
canvas_modules/common-canvas/src/common-properties/controls/datepicker-range/datepicker-range.jsx
canvas_modules/common-canvas/src/common-properties/controls/datepicker/datepicker.jsx
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.scss
canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx
canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx
canvas_modules/common-canvas/src/common-properties/controls/passwordfield/passwordfield.jsx
canvas_modules/common-canvas/src/common-properties/controls/slider/slider.jsx
canvas_modules/common-canvas/src/common-properties/controls/textarea/textarea.jsx
canvas_modules/common-canvas/src/common-properties/controls/textfield/textfield.jsx
canvas_modules/common-canvas/src/common-properties/controls/timefield/timefield.jsx

Fixes #1881 
After this change, `Layer` component is added in 2 files -
person who certified (a), (b) or (c) and I have not …

#1881 Added Layer component at control level

---

canvas_modules/harness/src/client/App.js

#1883 Fix Tooltips Test Harness Top Toolbar icons in v13

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/e2e/canvas/comment.cy.js

#1888 Enable HTML in Markdown

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/e2e/canvas/comment.cy.js

#1888 v12 Enable HTML in Markdown

---

docs/pages/03.03.01-context-menu-handler.md

Fix image URLs in docs

---

docs/pages/03.03.01-context-menu-handler.md

Fix image URLs in docs (#1898)

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/harness/src/client/components/custom-canvases/stages/multi-command-panel.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx
docs/pages/03.04-canvas-controller.md
docs/pages/03.10-command-stack.md

#1891 Enable multiple undo/redo button and panel  (#1904)

---

docs/mkdocs.yml
docs/pages/03-common-canvas.md
docs/pages/04-common-properties.md
docs/pages/04.01-parameter-definition.md
docs/pages/04.02-callbacks.md
docs/pages/04.03-ui-hints.md
docs/pages/04.06-custom-components.md
docs/pages/04.07-properties-controller.md
docs/pages/06-contributing.md

#1909 New common-canvas documentation required (part 2)

---

canvas_modules/common-canvas/src/object-model/config-utils.js

#1923 Palette node tooltips not working in Tiny App

---

canvas_modules/common-canvas/__tests__/common-properties/controls/checkbox-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js
canvas_modules/common-canvas/src/common-properties/controls/checkbox/checkbox.jsx
canvas_modules/common-canvas/src/common-properties/controls/checkbox/checkbox.scss

Fixes: #1927
PR for `v12.x` branch
it. …

#1927 Fixed Checkbox error/warning message showing incorrectly

---

docs/mkdocs.yml
docs/pages/01.01-flow-editor.md
docs/pages/01.01.01-nodes.md
docs/pages/01.08-tooltips.md
docs/pages/03.06.01-node-customization.md

#1893 New common-canvas documentation required - supernodes change

---

docs/pages/03-common-canvas.md
docs/pages/03.06.01-node-customization.md
docs/pages/03.06.02-comment-customization.md
docs/pages/04-common-properties.md

#1893 New common-canvas documentation required - final cleanup

---

docs/pages/03.06.01-node-customization.md

1954 Documentation for JSX Icons

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/toolbar/toolbar.scss

#1961 Ensure common-canvas uses  for focus color

---

canvas_modules/harness/src/client/components/sidepanel/canvas/sidepanel-canvas.jsx

#1965 The tip config checkboxes in the test harness don't work on v13

---

canvas_modules/harness/cypress/.eslintrc.js
canvas_modules/harness/cypress/e2e/canvas/decorators.cy.js
canvas_modules/harness/cypress/e2e/canvas/snap-to-grid.cy.js
canvas_modules/harness/cypress/e2e/canvas/undo-redo.cy.js
canvas_modules/harness/cypress/e2e/properties/expression-control.cy.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/link-cmds.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/operation-cmds.js
canvas_modules/harness/cypress/support/canvas/palette-cmds.js
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/canvas/utils-cmds.js
canvas_modules/harness/cypress/support/properties/expression-editor-cmds.js
canvas_modules/harness/cypress/support/properties/properties-cmds.js
canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js

#1974 Errors appear when editing Cypress files

---

docs/pages/01.06-notification-panel.md
docs/pages/03.09-read-only-or-locked-flows.md

#1976 Miscellaneous docs changes

---

canvas_modules/common-canvas/__tests__/command-stack/command-stack.js
docs/mkdocs.yml

#1989 Fix Typo in Elyra docs.

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/toolbar/toolbar.jsx
canvas_modules/harness/src/client/components/sidepanel/canvas/sidepanel-canvas.jsx
canvas_modules/harness/src/client/components/sidepanel/properties/sidepanel-properties.jsx

#1995 deprecation findDOMNode in React.StrictMode prevents edit

---

canvas_modules/common-canvas/src/tooltip/tooltip.jsx

#2003 Open Link in Tooltip in Safari browser.

---

canvas_modules/common-canvas/__tests__/context-menu/common-context-menu-test.js

#2005 Use React Testing Library for context-menu test 

---

.github/workflows/deploy-docs.yml

#2010 Deploy-docs run fails after commit is merged in main branch

---

canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/components/properties-buttons/properties-buttons.scss

#2018 Additional common-properties updates for Carbon 11

---

canvas_modules/common-canvas/locales/common-properties/locales/en.json
canvas_modules/common-canvas/src/common-properties/constants/constants.js
canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx

#2016 Expression Builder Dropdown should change label when switched between Fields and Functions.

---

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/checkbox_paramDef.json
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/harness/test_resources/parameterDefs/checkbox_paramDef.json

#2028 default_value condition not run when setting property values

---

.github/workflows/deploy-docs.yml

#2040 Deploy docs without versioning

---

canvas_modules/harness/src/client/components/custom-canvases/network/network-flow.json
canvas_modules/harness/src/client/components/custom-canvases/parallax/parallax-flow.json
docs/pages/03.06.01-node-customization.md

#2033 Support new link line types (part 3)

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/harness/src/client/components/custom-canvases/flows/flows-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/flows/flowsCanvas.json
canvas_modules/harness/src/client/components/custom-canvases/jsx-icons/jsx-icons-canvas-flow.json
canvas_modules/harness/src/client/components/custom-canvases/parallax/parallax-flow.json
canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/react-nodes-mapping-flow.json
canvas_modules/harness/src/client/components/custom-canvases/read-only/read-only.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages-card-node/stages-card-node-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stagesCanvas.json
docs/pages/01.01.02-links.md
docs/pages/03.04-canvas-controller.md
docs/pages/03.06.01-node-customization.md
docs/pages/03.06.03-link-customization.md

#2044 Miscellaneous changes to docs and sample apps

---

canvas_modules/common-canvas/src/command-actions/arrangeLayoutAction.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/harness/cypress/e2e/canvas/auto-layout-dagre.cy.js

#2022 Arrange Horizontal does not work when we have a detached link

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-new-link.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js
canvas_modules/harness/cypress/e2e/canvas/auto-layout-dagre.cy.js

#2051 With Ports link method new links are being drawn like freeform

---

canvas_modules/common-canvas/package.json
canvas_modules/harness/cypress/support/canvas/test-harness-cmds.js
canvas_modules/harness/cypress/support/properties/expression-editor-cmds.js
canvas_modules/harness/package.json

This is a workaround for https://github.com/elyra-ai/canvas/issues/2057 until we get a fix from Carbon …

#2057 Downgrade Carbon

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#2053 Refactor display comments code to be like display nodes code

---

canvas_modules/common-canvas/src/common-canvas/cc-text-toolbar.jsx

#2064 Fix outline-solid

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js

#2079 Add ability to adjust position of context toolbar for links

---

canvas_modules/common-canvas/locales/common-canvas/locales/en.json
canvas_modules/common-canvas/locales/common-canvas/locales/eo.json
canvas_modules/common-canvas/src/common-canvas/cc-text-toolbar.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/harness/src/client/components/custom-canvases/wysiwyg-comments/wysiwyg-comments-flow.json

#2083 With WYSIWYG comments IBM Plex Condensed font display incorrectly

---

canvas_modules/common-canvas/src/common-properties/form/Form.js
canvas_modules/common-canvas/src/common-properties/properties-controller.js

#2088 Title actions should not be displayed after form

---

canvas_modules/common-canvas/src/palette/palette.scss

#2099 Palette overflow-y set to auto

---

canvas_modules/common-canvas/package.json

#2103 Fix build failure

---

docs/pages/04.03-ui-hints.md

#2088 Title info doc updates

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss

#2106 Fix node editor resize button

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-objects.js
canvas_modules/common-canvas/src/object-model/pipeline-out-handler.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
docs/pages/03.04-canvas-controller.md

Fixes: #2115 2115
it.
(d) I understand and agree that this project …

#2115 Support collapsed super node resizing

---

canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.jsx
canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.scss
canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json

#2112 Title action buttons style updates

---

canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss

#2106 Fix node editor resize button position

---

canvas_modules/common-canvas/src/common-canvas/cc-context-toolbar.jsx
canvas_modules/common-canvas/src/common-canvas/cc-toolbar.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-sub-menu-item.jsx

#2135 Fix clickOutside fuctions in Toolbar

---

canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-sub-menu-item.jsx

#2135 Fix clickOutside fuctions in Toolbar (part 2)

---

canvas_modules/common-canvas/src/common-canvas/cc-toolbar.jsx

#2158 Update palette open/close icon in toolbar

---

canvas_modules/common-canvas/src/object-model/object-model.js

#2166 Nodes with looped links crash the UI in the test harness

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/object-model/config-utils.js

#2172 Make automatic focus on CommonCanvas opt-out

---

canvas_modules/common-canvas/__tests__/palette/palette-flyout-test.js
canvas_modules/common-canvas/src/object-model/config-utils.js
canvas_modules/common-canvas/src/palette/palette-flyout-content.jsx
canvas_modules/common-canvas/src/palette/palette-flyout.jsx
canvas_modules/common-canvas/src/palette/palette.jsx
canvas_modules/common-canvas/src/palette/palette.scss
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel/canvas/sidepanel-canvas.jsx
docs/pages/01.02-palette.md
docs/pages/03.02.01-canvas-config.md

#2176 Add button to node palette

---

canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx

#2178 Disable scroll in NumberField

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-links.js
canvas_modules/harness/cypress/e2e/canvas/links.cy.js
canvas_modules/harness/cypress/e2e/canvas/nodes-resize.cy.js

#2162 Fix vertical links crossing over each other

---

canvas_modules/common-canvas/package.json
canvas_modules/harness/package.json

#2180 Upgrade to react-redux@8

---

canvas_modules/harness/src/client/components/custom-canvases/stages/app-decoration.jsx
canvas_modules/harness/src/client/components/custom-canvases/stages/stages-canvas.jsx

#2184 Add JSX decoration example to Stages sample application

---

canvas_modules/common-canvas/src/object-model/config-utils.js

#2194 Prevent canvas refresh when palette header is specified

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/keyboard-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-pipeline.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-accessibility.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-textarea.js
canvas_modules/common-canvas/src/object-model/config-utils.js
canvas_modules/common-canvas/src/toolbar/toolbar-divider-item.jsx
canvas_modules/harness/cypress/e2e/canvas/zoom.cy.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel/canvas/sidepanel-canvas.jsx

#1438 Accessibility: Tabbing - Keyboard navigation of canvas objects

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-builder.scss
canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx
canvas_modules/common-canvas/src/common-properties/controls/expression/expression.scss

#2199 Allow expression text editor to be expandable

---

canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-content-category.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-content-search.jsx

#2211 Fix Accessibility Issues for palette

---

canvas_modules/common-canvas/src/palette/palette-flyout-content-search.jsx

#2215 Fix Accessibility Issues for palette search

---

canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.jsx
canvas_modules/common-canvas/src/toolbar/toolbar-button-item.jsx

#2218 Fix accessibility violations

---

canvas_modules/harness/src/client/App.js

#2220 SubAreas sample toolbar - 'Save' button should have a label 

---

canvas_modules/harness/functional_test.sh

Fixes: #2226 
Changed browser from `Electron` to `Chrome` for cypress tests.
person who certified (a), (b) or (c) and I have not …

#2226 Fixed cypress tests in Actions

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx

 #2232 Expression Builder: After editing in flyout, user needs to click icon twice to open Editor

---

canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss
canvas_modules/common-canvas/src/common-properties/components/empty-table/empty-table.scss

#2236 [SDG] Differential privacy ux issues - Fix font type for properties label

---

canvas_modules/common-canvas/__tests__/common-properties/controls/oneofselect-test.js
canvas_modules/common-canvas/__tests__/common-properties/panels/tearsheet-test.js
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx
canvas_modules/harness/package.json

#2205 Upgrade @carbon/react to 1.71.0

---

canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-canvas.jsx
canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-flow.json
canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-palette.json
canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-react.jsx
canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-template.json
canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt.scss
canvas_modules/harness/src/client/components/sidepanel/canvas/sidepanel-canvas.jsx
canvas_modules/harness/src/client/constants/harness-constants.js
canvas_modules/harness/src/styles/custom-canvases.scss

#2252 Create a sample app that shows a prompt interface

---

canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx
canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss

#2257 Action Image alignment issue

---

canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss

#2261 Properties sizing button hidden by bottom panel

---

canvas_modules/common-canvas/src/palette/palette-flyout-content.jsx
canvas_modules/common-canvas/src/palette/palette.scss

#2270 Canvas palette not loading/displayed in Safari browser

---

canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss

#2283 Custom Controls do not take up full width when there is an action button on right

---

canvas_modules/common-canvas/src/common-properties/controls/controls.scss

#2285 Common Properties Code control pushes action button out of panel

---

docs/pages/04-common-properties.md

#2289 Common Properties Right Flyout Styling Documentation (minor changes)

---

canvas_modules/common-canvas/src/object-model/object-model.js

#2309 Click with shift doesn't remove selections

---

canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-canvas/cc-top-panel.jsx

#2311 Top panel re-renders uncessasarily

---

canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx

#2314 Disabled palette items need aria-disabled

---

canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/common-canvas/src/palette/palette-content-list.jsx
canvas_modules/common-canvas/src/palette/palette-flyout-content-category.jsx

#2319 Keyboard accessibility of palette tooltip

---

canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
canvas_modules/harness/test_resources/parameterDefs/structurelisteditor_paramDef.json

#2321 Single select table with moveable rows and no Delete icons

---

canvas_modules/common-canvas/__tests__/common-properties/panels/tearsheet-test.js
canvas_modules/common-canvas/src/common-properties/components/main-editor-properties-buttons/main-editor-properties-buttons.jsx
canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.jsx
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx

#2323 Tearsheet- Flow Properties- Should be able to disable Save for invalid job parameters

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#2328 SVG Elements Lack Accessible Names in Common Canvas Nodes

---

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx

#2332 Include Codemirror aria-label

---

canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx

#2336 Accessibility Violation in Disabled Control Label

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/client/App.js

#2342 Accessibility violation in the empty canvas page

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/object-model/object-model.js

#2340 Miscellaneous function signature improvements in Canvas Controller

---

canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-canvas.jsx

#2348 Specify node type in Prompt sample app

---

canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/mapping-container-node.jsx
canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/react-nodes-mapping-canvas.jsx

#2354 Update Mapping sample app to have editable column names

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/cypress/e2e/canvas/keyboard-navigation.cy.js
canvas_modules/harness/cypress/support/canvas/comments-cmds.js
canvas_modules/harness/cypress/support/canvas/key.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/cypress/support/canvas/operation-cmds.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js
docs/pages/03.05-keyboard-support.md

#2356 Keyboard equivalents needed for different types of mouse' click'

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#2362 Error handling problems with canvasController.moveFocusTo

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#2366 updateComment time logger message does not have an end

---

canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/index.js
canvas_modules/common-canvas/src/common-canvas/d3-zoom-extension/src/zoom.js

#2371 Update zoom extension to be in-sync with D3 zoom code

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#2373 Hovering mouse pointer over node causes focus to be lost

---

canvas_modules/common-canvas/types/common-canvas.ts
canvas_modules/common-canvas/types/index.test-d.ts

#2377 Typescript definition missing palette properties

---

canvas_modules/common-canvas/types/common-canvas.ts
canvas_modules/common-canvas/types/index.test-d.ts

#2379 Incorrect id property in Typescript test

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js

#2360 MoveFocusTo can sometimes have an error in complex refresh scenarios

---

canvas_modules/common-canvas/types/common-canvas.ts
canvas_modules/common-canvas/types/common-properties.ts

#2398 TypeScript definitions do not work with isolatedModules

---

canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx

#2403 Show invalid number error when entering non numeric characters in empty numberfield control

---

canvas_modules/common-canvas/src/common-canvas/constants/canvas-constants.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-zoom.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js
canvas_modules/harness/src/client/App.js
canvas_modules/harness/src/client/components/sidepanel/canvas/sidepanel-canvas.jsx

#2408 Canvas background with vector dots or grid option

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss

#2408 Canvas background with vector dots or grid option (part 3)

---

canvas_modules/common-canvas/types/common-properties-schema-types/uihints-v3.ts
canvas_modules/common-canvas/types/common-properties.ts
canvas_modules/common-canvas/types/index.test-d.ts
docs/pages/04-common-properties.md
docs/pages/04.06-custom-components.md

#2430 Update typescript declarations for Custom Actions

---

canvas_modules/common-canvas/src/command-actions/createCommentAction.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#2434 Improve creation of comments code -- for consistency

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#2434 Improve creation of comments code -- for consistency (Part 2)

---

canvas_modules/common-canvas/__tests__/object-model/object-model-api-test.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/object-model/api-pipeline.js
canvas_modules/harness/cypress/support/canvas/verification-cmds.js

#2434 Improve creation of comments code -- for consistency (Part 3)

---

canvas_modules/common-canvas/types/common-canvas.ts

#2432 Improve TypeScript definitions of EditActionData (Director's Cut)

---

canvas_modules/common-canvas/types/canvas-controller.ts
canvas_modules/common-canvas/types/common-canvas.ts

#2442 Refactor common-canvas.ts for better structure

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/harness/cypress/e2e/canvas/clipboard.cy.js

#2446 Pasting to mouse position not working when background grid displayed

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-zoom.js

#2448 Bug: Tabbing doesn't focus nodes

---

canvas_modules/common-canvas/types/canvas-controller.ts
canvas_modules/common-canvas/types/common-canvas.ts
docs/mkdocs.yml
docs/pages/03.06.04-canvas-customization.md

#2450 Include enableCanvasLayout in CanvasConfig interface

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.scss

#2452 Bug: Navigating out of nested nodes

---

canvas_modules/common-canvas/types/canvas-controller.ts
docs/pages/03.02.01-canvas-config.md
docs/pages/03.11-internal-actions.md

… follow Common Canvas architecture (Part 2)
Fixes: #2463 
it.
(d) I …

Int actions

---

docs/mkdocs.yml
docs/pages/03.12-node-properties-management.md

#2467 Write a new page for docs about how to manage node properties

---

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/harness/cypress/e2e/canvas/keyboard-navigation.cy.js
canvas_modules/harness/cypress/support/canvas/node-cmds.js

#2471 Focus is lost when moving or sizing a node with the keyboard

---

canvas_modules/common-canvas/types/common-canvas.ts

This PR fixes the issue mentioned in https://ibm-cloud.slack.com/archives/C598XEX8S/p1745298112999269
Fixes https://github.com/elyra-ai/canvas/issues/2479
(c) The contribution was provided …

Typescript fix for isolatedModules

---

canvas_modules/common-canvas/types/common-canvas.ts

#2475 Position info hardcoded in TS declarations

---

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-zoom.js
canvas_modules/harness/cypress/support/canvas/canvas-cmds.js

#2486 Realtime node selection

---

canvas_modules/common-canvas/src/common-properties/components/virtualized-grid/virtualized-grid.jsx
canvas_modules/common-canvas/src/common-properties/controls/toggletext/toggletext.jsx

#2490 Fix accessibility violations in tables in toggletext

---

canvas_modules/common-canvas/src/common-properties/components/empty-table/empty-table.jsx
canvas_modules/harness/test_resources/parameterDefs/columnSelectionPanel_multiInput_paramDef.json

#2492 Accessibility Violation in disabled Add Columns text

---

canvas_modules/common-canvas/build.sh

#2488 Run TypeScript tests during the build

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#2499 Accessibility violation in canvas node label edit icon

---

canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.scss
canvas_modules/harness/src/client/components/custom-components/CustomFlexibleTableCtrl.jsx
canvas_modules/harness/src/styles/App.scss

fixes #2501 
Before:
After:
it.
(d) I understand and agree that this …

#2501 Accessibility viiolation on empty data tables

---

canvas_modules/common-canvas/src/common-properties/controls/readonly/readonly.jsx

#2503 Accessibility Violation in disabled properties field type

---

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/harness/src/client/components/custom-canvases/react-nodes-carbon/react-nodes-carbon-canvas.jsx

#2505 Focus highlight has no gap with react based nodes

---

canvas_modules/common-canvas/src/common-properties/controls/timefield/timefield.jsx
canvas_modules/common-canvas/src/common-properties/panels/text-panel/text-panel.jsx

#2503 Accessibility violation in controls with blank label 

---

canvas_modules/common-canvas/src/palette/palette-content-list-item.jsx
canvas_modules/common-canvas/src/palette/palette.scss

#2527 Accessibility Violations in canvas palette search

---

canvas_modules/common-canvas/jest-setup.js
canvas_modules/common-canvas/package.json
canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
canvas_modules/common-canvas/src/common-properties/components/virtualized-grid/virtualized-grid.jsx

#2529 Fix unit tests due to new tanstack virtual v3.13.7

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#2531 canvasController.selectAll() causes canvas DOM element focus

---

canvas_modules/common-canvas/src/palette/palette.scss

#2533 Palette search results shows a scrollbar when 'Show scroll bars' is set to 'Always' on the Mac

---

canvas_modules/common-canvas/__tests__/common-properties/controls/oneofselect-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/oneofselect_paramDef.json
canvas_modules/common-canvas/src/common-properties/common-properties.jsx
canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx
canvas_modules/common-canvas/src/common-properties/properties-controller.js
canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
canvas_modules/harness/src/client/App.js
canvas_modules/harness/test_resources/parameterDefs/oneofselect_paramDef.json
docs/pages/04.02-callbacks.md

#2535 Custom shouldFilterItem callback

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/types/canvas-controller.ts
docs/pages/03.04-canvas-controller.md

#2549 Fix documentation for ClassName methods of the canvas controller

---

canvas_modules/common-canvas/src/common-properties/components/virtualized-grid/virtualized-grid.scss
canvas_modules/common-canvas/src/common-properties/controls/expression/expression.scss
canvas_modules/common-canvas/src/common-properties/controls/list/list.scss
canvas_modules/common-canvas/src/common-properties/controls/readonlytable/readonlytable.scss
canvas_modules/common-canvas/src/common-properties/controls/selectcolumns/selectcolumns.scss
canvas_modules/common-canvas/src/common-properties/controls/structurelisteditor/structurelisteditor.scss
canvas_modules/common-canvas/src/common-properties/panels/control/control.scss
canvas_modules/common-canvas/src/common-properties/panels/text-panel/text-panel.scss

#2555 Remove opacity to fix accessibility violations in contols using tables

---

canvas_modules/common-canvas/src/common-canvas/cc-bottom-panel.jsx
canvas_modules/common-canvas/src/common-canvas/cc-panels.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx

#2577 Containing div not defined correctly in cc-panels.jsx

---

canvas_modules/common-canvas/__tests__/common-properties/controls/structurelisteditor-test.js
canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js
canvas_modules/common-canvas/__tests__/test_resources/json/form-editstyle-test.json
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structurelisteditor_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
canvas_modules/common-canvas/src/common-properties/form/EditorForm.js
canvas_modules/harness/test_resources/parameterDefs/structurelisteditor_paramDef.json

Fixes #2521 
Added this table in `struturelisteditor_paramDef.json` under `Conditions` for testing -
person who certified (a), (b) …

#2521 Fixed - Visible condition is not working properly inside subpanel for complex type

---

canvas_modules/common-canvas/__tests__/common-properties/conditions/panel-conditions-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/expression-test.js
canvas_modules/common-canvas/__tests__/common-properties/controls/numberfield-test.js
canvas_modules/harness/cypress/e2e/properties/expression-control.cy.js

#2553 Enable skipped tests for common-properties-updated

---

canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/harness/src/styles/App.scss

#2612 Bottom Panel Width Issue with right flyout

---

canvas_modules/common-canvas/src/command-actions/createAutoNodeAction.js
canvas_modules/common-canvas/src/common-canvas/canvas-controller.js

#2630 Auto-create of node should not cause focus to move to canvas

---

canvas_modules/common-canvas/src/common-canvas/keyboard-utils.js

#2646 Logging activation using keyboard no longer working

---

canvas_modules/common-canvas/build.sh

#2642 Adjust build script to deploy test-harness cloud

---

canvas_modules/common-canvas/src/common-canvas/keyboard-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
canvas_modules/common-canvas/src/common-canvas/svg-canvas-pipeline.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-accessibility.js
canvas_modules/common-canvas/src/object-model/layout-dimensions.js
canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-canvas.jsx
docs/pages/03.05-keyboard-support.md

#2657 Keyboard accessibility: ports should be focusable

---

canvas_modules/common-canvas/src/common-canvas/keyboard-utils.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js

#2657 Keyboard accessibility: ports should be focusable (Part 2)

---

canvas_modules/common-canvas/__tests__/common-properties/controls/checkbox-test.js
canvas_modules/common-canvas/__tests__/test_resources/paramDefs/checkbox_paramDef.json
canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
canvas_modules/harness/test_resources/parameterDefs/checkbox_paramDef.json

#2664 Select all in table should not select checkboxes that are hidden or disabled

---

canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss

#2705 Properties panel resize button has no background

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/cc-right-flyout.jsx
canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
canvas_modules/common-canvas/src/object-model/object-model.js
canvas_modules/common-canvas/src/object-model/redux/canvas-store.js

#2724 Allow application to override minumum width for right flyout

---

canvas_modules/common-canvas/locales/common-properties/locales/de.json
canvas_modules/common-canvas/locales/common-properties/locales/es.json
canvas_modules/common-canvas/locales/common-properties/locales/fr.json
canvas_modules/common-canvas/locales/common-properties/locales/it.json
canvas_modules/common-canvas/locales/common-properties/locales/ja.json
canvas_modules/common-canvas/locales/common-properties/locales/ko.json
canvas_modules/common-canvas/locales/common-properties/locales/pt-br.json
canvas_modules/common-canvas/locales/common-properties/locales/sv.json
canvas_modules/common-canvas/locales/common-properties/locales/zh-CN.json
canvas_modules/common-canvas/locales/common-properties/locales/zh-TW.json

For https://github.com/elyra-ai/canvas/issues/2727
it.
(d) I …

Translation 20250926.104509

---

canvas_modules/common-canvas/__tests__/common-properties/components/fieldpicker-test.js
canvas_modules/common-canvas/src/common-properties/panels/control/control.scss

Closes #2734 
**Before -**
**After -**
it. …

#2734 Don’t add spacing for hidden control

---

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-pipeline.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-accessibility.js
canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-det-link.js

#2739 Keyboard navigation tab groups index is reset incorrectly
