canvas_modules/harness/cypress/integration/properties/common-properties-actions.js, canvas_modules/harness/cypress/integration/properties/custom-controls.js, canvas_modules/harness/cypress/integration/properties/readonly-controls.js, canvas_modules/harness/cypress/support/index.js, canvas_modules/harness/cypress/support/properties/properties-cmds.js, canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js
- Modified **cy.saveWideflyout()** command to **cy. saveWideFlyoutHavingName(panelName)** because  **cy.saveWideflyout()** didn't work when multiple wide flyouts are open.
- Created a new file for all verification commands. This is similar to `verification-cmds.js` file in `cypress/support/canvas` folder
by me, under the …
=> Implemented Common Properties Actions Unit Test using Cypress framework

canvas_modules/common-canvas/__tests__/common-properties/operators/dmMeasurementEquals-test.js, canvas_modules/common-canvas/src/common-properties/properties-controller.js, canvas_modules/common-canvas/src/common-properties/ui-conditions/conditions-utils.js
=> Fix datasetmetadata conditions not being ran on startup

canvas_modules/common-canvas/src/notification-panel/notification-panel.scss
Fixes Carbon compatibility for https://github.com/elyra-ai/canvas/issues/104
Styling on Carbon components needs to use identical scss selectors if a Carbon theme is used. Though it's not specified in the test harness, if @elyra-ai/canvas were to be used with theming on Carbon components, the scss selectors need to be properly set.
Also fixes notification message scrolling issue introduced by the fix for no-click-through when the notification panel is open.
of my knowledge, is covered under an appropriate …
=> #104 notification center styling compatibility

canvas_modules/common-canvas/src/notification-panel/notification-panel.scss, canvas_modules/harness/cypress/support/properties/properties-cmds.js
Fixes: https://github.com/elyra-ai/canvas/issues/187
Notification message title and messages will now wrap on long words instead of only on word breaks.
(c) The contribution was provided …
=> #187 Notification Messages overflow on long words

canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx
Fixes https://github.com/elyra-ai/canvas/issues/251
it.
(d) I …
=> Numberfield default value set to empty string when default value is undefined

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
=> #253 CanvasController.creatNodeLinks does not return the links created

canvas_modules/common-canvas/locales/common-properties/locales/en.json, canvas_modules/common-canvas/locales/common-properties/locales/eo.json, canvas_modules/common-canvas/src/common-properties/constants/constants.js, canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx, canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx
Fixes https://github.com/elyra-ai/canvas/issues/268
I added test strings in `ja.json` and `de.json`.
**Tooltip translated in German language -** 
**Tooltip translated in Japanese language -**  …
=> #268 Translate dropdown menu tooltips

canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-builder.scss
Adds styling fixes for https://github.com/elyra-ai/canvas/issues/250
The original styling didn't account for situations where the operators would overflow into more rows, and there wasn't padding set for those.
Before:
After:  …
=> #250 Styling fix - Implement new design for Expression Builder

canvas_modules/common-canvas/src/common-canvas/common-canvas.scss
=> #323 Right flyout drop shadow should not extend above top of flyout

canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-builder.jsx, canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx
Fixes https://github.com/elyra-ai/canvas/issues/325
The original error cases can only be hit when "Show Expression Validate Link" is set to `Off` in the Common Properties settings flyout before opening a paramDef.
permitted to submit under a different license), as …
=> #325 Expression Builder empty value validation error doesn't clear on change

canvas_modules/common-canvas/__tests__/common-properties/components/title-editor-test.js, canvas_modules/common-canvas/__tests__/common-properties/form/form-test.js, canvas_modules/common-canvas/__tests__/test_resources/json/form-actions-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-editstyle-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-placement-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-structure-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-structure2-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-test.json, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/Filter_paramDef.json, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/empty_paramDef.json, canvas_modules/common-canvas/package.json, canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.jsx, canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.scss, canvas_modules/common-canvas/src/common-properties/form/Form.js, canvas_modules/common-canvas/src/common-properties/form/PropertyDef.js, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss, canvas_modules/harness/cypress/integration/canvas/tips.js, canvas_modules/harness/src/client/App.js, canvas_modules/harness/src/client/components/sidepanel-properties.jsx, canvas_modules/harness/test_resources/parameterDefs/Conditions_paramDef.json, canvas_modules/harness/test_resources/parameterDefs/Filter_paramDef.json, canvas_modules/harness/test_resources/parameterDefs/Spark_SelectColumns_paramDef.json, canvas_modules/harness/test_resources/parameterDefs/empty_paramDef.json
Addresses https://github.com/elyra-ai/canvas/issues/419
An option in the common properties config panel has been added to display the subtitle, and `empty_paramDef.json` has been updated to show a working demo of an icon in the subtitle.
permitted to submit under a …
=> #419 Improve Common Properties TitleEditor

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss, canvas_modules/harness/cypress/support/canvas/node-cmds.js
=> #528 Wide labels with closely positiond nodes doesn't display edit icon

canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumns-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js, canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx, canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss, canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx, canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx, canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.scss, canvas_modules/common-canvas/src/common-properties/constants/constants.js, canvas_modules/common-canvas/src/common-properties/controls/control-factory.js
Fixes: https://github.com/elyra-ai/canvas/issues/599
Showing Text panel style label for following controls -
- List
- Readonlytable
- Structurelisteditor
- Structuretable
- Selectcolumns
- Someofselect
No change in label for other controls.
permitted to submit under a …
=> #599 Table rows and headers are 32px tall and table title in Text panel style

canvas_modules/common-canvas/__tests__/_utils_/table-utils.js, canvas_modules/common-canvas/__tests__/common-properties/controls/list-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/readonlytable-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumns-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/structurelisteditor-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js, canvas_modules/common-canvas/__tests__/common-properties/defaults-test.js, canvas_modules/common-canvas/__tests__/common-properties/panels/columnselection-test.js, canvas_modules/common-canvas/__tests__/common-properties/panels/summary-test.js, canvas_modules/common-canvas/locales/common-properties/locales/en.json, canvas_modules/common-canvas/locales/common-properties/locales/eo.json, canvas_modules/common-canvas/src/common-properties/components/empty-table/empty-table.jsx, canvas_modules/common-canvas/src/common-properties/components/empty-table/empty-table.scss, canvas_modules/common-canvas/src/common-properties/components/empty-table/index.js, canvas_modules/common-canvas/src/common-properties/components/moveable-table-rows/moveable-table-rows.jsx, canvas_modules/common-canvas/src/common-properties/constants/constants.js, canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx, canvas_modules/common-canvas/src/common-properties/controls/abstract-table.scss, canvas_modules/common-canvas/src/common-properties/controls/list/list.jsx, canvas_modules/common-canvas/src/common-properties/controls/readonlytable/readonlytable.jsx, canvas_modules/common-canvas/src/common-properties/controls/selectcolumns/selectcolumns.jsx, canvas_modules/common-canvas/src/common-properties/controls/structurelisteditor/structurelisteditor.jsx, canvas_modules/common-canvas/src/common-properties/controls/structuretable/structuretable.jsx, canvas_modules/harness/cypress/integration/properties/structure-list-editor-table-control.js, canvas_modules/harness/cypress/support/properties/properties-cmds.js, canvas_modules/harness/test_resources/parameterDefs/list_paramDef.json
Fixes https://github.com/elyra-ai/canvas/issues/608
Added empty table content for controls - 
- List
- Readonlytable
- Selectcolumns
- Structurelisteditor
- Structuretable
- Fieldpicker
Empty table content general format -
```
text: To begin, click "{button_label}"
button: tertiary button - label same as the Add button label in the table
```
- Text can be customized by the host applications for **all** controls by passing `"{parameter-id}.empty.table.text"` in resources in parameter definition.
For example - 
```
"resources": {
"list_string.empty.table.text": "This is a custom empty text for list."
}
```
- Button label will be different for different controls -
**Add value** - List, structurelisteditor
**Add columns** - Selectcolumns, Structuretable, Fieldpicker
**Edit** or any custom …
=> #608 When table is empty, show customizable text and Add button

canvas_modules/common-canvas/__tests__/common-properties/controls/readonlytable-test.js, canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx, canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx, canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.scss, canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
Fixes https://github.com/elyra-ai/canvas/issues/693
For readonlyTable with single row selection, setting `selectable = false` in `virtualized-table.jsx`. 
Nothing should happen when the user hovers or clicks directly on the readonlyTable.
permitted to submit under a …
=> #693 ReadonlyTable with single row selection is non-interactive

canvas_modules/common-canvas/src/common-canvas/common-canvas.jsx, canvas_modules/common-canvas/src/common-properties/actions/button/button.jsx, canvas_modules/common-canvas/src/common-properties/actions/image/image.jsx, canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx, canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss, canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.jsx, canvas_modules/common-canvas/src/common-properties/components/validation-message/validation-message.jsx, canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx, canvas_modules/common-canvas/src/common-properties/constants/constants.js, canvas_modules/common-canvas/src/common-properties/controls/checkbox/checkbox.jsx, canvas_modules/common-canvas/src/common-properties/controls/checkbox/checkbox.scss, canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-operator.jsx, canvas_modules/common-canvas/src/common-properties/controls/readonly/readonly.jsx, canvas_modules/common-canvas/src/common-properties/controls/textarea/textarea.jsx, canvas_modules/common-canvas/src/common-properties/controls/textfield/textfield.jsx, canvas_modules/common-canvas/src/common-properties/panels/sub-panel/cell.jsx, canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx, canvas_modules/common-canvas/src/tooltip/tooltip-wrapper.jsx, canvas_modules/common-canvas/src/tooltip/tooltip.jsx, canvas_modules/common-canvas/src/tooltip/tooltip.scss, canvas_modules/harness/cypress/integration/canvas/tips.js, canvas_modules/harness/cypress/support/canvas/verification-cmds.js, canvas_modules/harness/cypress/support/properties/properties-cmds.js, canvas_modules/harness/cypress/support/properties/properties-verification-cmds.js, canvas_modules/harness/src/client/components/custom-canvases/explain2/explain2.scss
Fixes https://github.com/elyra-ai/canvas/issues/731
- For common-properties, tooltip will be visible on clicking "i" icon.
- For common-canvas, toolbar, palette - tooltip will be visible on mouse hover. 
- Updated tooltip CSS to match with carbon. 
permitted to submit …
=> #731 Align elyra tooltip with carbon tooltip

canvas_modules/common-canvas/src/toolbar/toolbar-action-item.jsx, canvas_modules/common-canvas/src/tooltip/tooltip.jsx
Fixes #751 
- Events for common-canvas, toolbar, palette - mouseover, mouseleave, mousedown
- Events for common-properties - click, focus, blur, tabIndex
- Not showing tootips for disabled toolbar icons
in the …
=> #751 Fixed toolbar tooltip issues

README.md
The URL provided in the readme instructions doesn't point to this repo:
```
$ git clone git@github.com:elyra/canvas.git
Cloning into 'canvas'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
``` …
=> Update clone instructions to valid git URL

canvas_modules/common-canvas/__tests__/common-properties/components/fieldpicker-test.js, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/expressionControl_paramDef.json, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/fieldpicker_paramDef.json, canvas_modules/common-canvas/src/common-properties/components/components.scss, canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.jsx, canvas_modules/common-canvas/src/common-properties/components/field-picker/field-picker.scss, canvas_modules/common-canvas/src/common-properties/components/truncated-content-tooltip/index.js, canvas_modules/common-canvas/src/common-properties/components/truncated-content-tooltip/truncated-content-tooltip.jsx, canvas_modules/common-canvas/src/common-properties/components/truncated-content-tooltip/truncated-content-tooltip.scss, canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx, canvas_modules/common-canvas/src/common-properties/controls/readonly/readonly.jsx, canvas_modules/common-canvas/src/common-properties/controls/readonly/readonly.scss, canvas_modules/harness/test_resources/parameterDefs/expressionControl_paramDef.json, canvas_modules/harness/test_resources/parameterDefs/fieldpicker_paramDef.json
Fixes #858 
Field picker table - 
Expression control - 
it.
(d) I …
=> #858 Enable tooltips for table cells in fieldpicker and expression control tables

canvas_modules/common-canvas/locales/command-actions/locales/en.json, canvas_modules/common-canvas/locales/command-actions/locales/eo.json, canvas_modules/common-canvas/src/command-actions/commonPropertiesAction.js, canvas_modules/common-canvas/src/common-properties/common-properties.jsx, canvas_modules/common-canvas/src/common-properties/constants/constants.js, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx, canvas_modules/common-canvas/src/common-properties/util/property-utils.js, canvas_modules/harness/cypress/integration/canvas/tips.js, canvas_modules/harness/src/client/App.js
Fixes #890 
Added callback method `propertiesActionLabelHandler()`.
Setting custom label for "Save properties" action in test harness -
(c) The contribution was provided directly to me by some …
=> #890 Added callback to allow Undo/Redo label override for Save properties action

canvas_modules/common-canvas/__tests__/common-properties/controls/textfield-test.js, canvas_modules/common-canvas/src/common-properties/controls/textfield/textfield.jsx
=> #910 Set textfield to null when no default value is provided

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js, canvas_modules/common-canvas/__tests__/common-properties/components/main-editor-proprties-button-test.js, canvas_modules/common-canvas/__tests__/common-properties/ui-parameters-test.js, canvas_modules/common-canvas/src/common-properties/components/properties-buttons/properties-buttons.jsx, canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.jsx, canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.scss, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss, canvas_modules/harness/cypress/integration/canvas/nodes.js, canvas_modules/harness/cypress/integration/canvas/tips.js, canvas_modules/harness/cypress/support/properties/properties-cmds.js
Fixes #969 
- All buttons and input text in title has height 32px
**Title without heading -**
**Title with heading -**
**Title with warning/error -**
(c) The contribution was provided directly …
=> #969 Replaced Close button with X icon when applyOnBlur is set

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/action_paramDef.json, canvas_modules/common-canvas/src/tooltip/tooltip.jsx, canvas_modules/harness/cypress/integration/properties/actions.js, canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json
=> #980 Fixed left aligned long tooltip overlaps tooltip-trigger element

canvas_modules/common-canvas/src/common-canvas/cc-contents.jsx
Fixes #1011. An error was showing in the console when the drag event was triggered but the event target didn't have the field `e.target.className.baseVal`. This adds a check for those fields before accessing to prevent an error.  …
=> Fix console error

canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx, canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx, canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx, canvas_modules/harness/test_resources/parameterDefs/structurelisteditor_paramDef.json, canvas_modules/harness/test_resources/parameterDefs/structuretable_paramDef.json
Fixes #1036 
@matthoward366 To see individual deltas for each column, uncomment lines **335-352** in `virtualized-table.jsx` file. 
After verification, I will remove these comments - 
(c) The …
=> #1036 Updated resizable columns algorithm

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js, canvas_modules/common-canvas/src/common-properties/properties-controller.js
Fixes #1094 
To test, use this paramDef - [DRJobs-3339.json.zip](https://github.com/elyra-ai/canvas/files/8931855/DRJobs-3339.json.zip)
`table_name` is a hidden required property. Verify error message for `table_name` is filtered in [getRequiredErrorMessages()](https://github.com/elyra-ai/canvas/blob/main/canvas_modules/common-canvas/src/common-properties/properties-controller.js#L1397) and [applyPropertyChanges()](https://github.com/elyra-ai/canvas/blob/main/canvas_modules/harness/src/client/App.js#L1322) methods when filterHiddenDisable is set to true. 
(b) The …
=> #1094 Filter error messages for control type hidden when filterHiddenDisable is set

canvas_modules/harness/src/client/components/custom-canvases/detached-links/detached.scss
=> #1148 Use transparent background for detached-canvas sample app nodes

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js, canvas_modules/common-canvas/src/common-properties/actions.js, canvas_modules/common-canvas/src/common-properties/components/wide-flyout/wide-flyout.jsx, canvas_modules/common-canvas/src/common-properties/panels/summary/summary.jsx, canvas_modules/common-canvas/src/common-properties/properties-controller.js, canvas_modules/common-canvas/src/common-properties/properties-store.js, canvas_modules/common-canvas/src/common-properties/reducers/ok-button-disable.jsx, canvas_modules/common-canvas/src/common-properties/reducers/wide-flyout-primary-button-disable.jsx, canvas_modules/harness/src/client/App.js, canvas_modules/harness/src/client/components/sidepanel-properties.jsx
Fixes #1160 
For testing, set summaryPanel id here in test harness -  …
=> #1160 Enable/disable summaryPanel OK button from properties controller

scripts/publish_modules.sh
#1172 
npm registry URL copied from here - https://docs.npmjs.com/cli/v6/using-npm/registry
person who certified (a), (b) or (c) …
=> #1172 Add registry flag in npm publish

canvas_modules/common-canvas/src/palette/palette.scss
=> #1192 Palette-flyout-catgories height has invalid calculation syntax

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structurelisteditor_paramDef.json, canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.scss, canvas_modules/harness/test_resources/parameterDefs/structurelisteditor_paramDef.json
Fixes #1210 
Multi-line text -
Single line text -
it.
(d) I …
=> #1210 Added padding for empty table placeholder text

canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js, canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.jsx, canvas_modules/common-canvas/src/common-properties/components/virtualized-table/virtualized-table.scss
=> #1215 Support info icons in table header labels

.github/workflows/build.yml
=> #1289 Cancel old build jobs when new commit is pushed to a PR

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/Filter_paramDef.json, canvas_modules/common-canvas/src/common-properties/components/properties-modal/properties-modal.jsx, canvas_modules/common-canvas/src/common-properties/constants/form-constants.js, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main-widths.scss, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.scss, canvas_modules/harness/src/client/components/sidepanel-properties.jsx, canvas_modules/harness/src/client/constants/constants.js, canvas_modules/harness/test_resources/parameterDefs/Filter_paramDef.json
Fixes #1324 
Signed-off-by: Neha-Gokhale <Neha.Gokhale@ibm.com>
- Supports "max" option in [Editor size](https://github.com/elyra-ai/canvas/wiki/3.2-Common-Properties--UI-Hints#ui-hints) having 900px width.
- When "large" is specified the properties panel has a width of 640px and with a resize button that allows the panel to be increased in size up to the "max" size which is 900px.
- When "max" is specified the properties panel is has a width of 900px and no resize button is displayed.
of my knowledge, is …
=> #1324 Support 'max' option for editor_size in common-properties

canvas_modules/common-canvas/__tests__/common-properties/components/control-item-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/multiselect-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/oneofselect-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumn-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/selectschema-test.js, canvas_modules/common-canvas/__tests__/common-properties/form/form-test.js, canvas_modules/common-canvas/__tests__/test_resources/json/form-actions-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-editstyle-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-structure-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-structure2-test.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-test-condition.json, canvas_modules/common-canvas/__tests__/test_resources/json/form-test.json, canvas_modules/common-canvas/locales/common-properties/locales/en.json, canvas_modules/common-canvas/locales/common-properties/locales/eo.json, canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.jsx, canvas_modules/common-canvas/src/common-properties/components/control-item/control-item.scss, canvas_modules/common-canvas/src/common-properties/constants/constants.js, canvas_modules/common-canvas/src/common-properties/form/ControlInfo.js, canvas_modules/common-canvas/src/common-properties/form/EditorForm.js, canvas_modules/common-canvas/src/common-properties/form/ParameterInfo.js, canvas_modules/harness/cypress/integration/canvas/tips.js
Fixes #1333 
- If the majority of the fields are required, mark only the optional field labels with `(optional)`.
- If the majority of the fields are optional, mark only the required field labels with `(required)`.
permitted to submit under a different license), as …
=> #1333 Show 'required' or 'optional' indicator for properties labels

canvas_modules/common-canvas/__tests__/test_resources/paramDefs/checkbox_paramDef.json, canvas_modules/common-canvas/src/tooltip/tooltip.scss, canvas_modules/harness/test_resources/parameterDefs/checkbox_paramDef.json
Fixes #1372 
Signed-off-by: Neha-Gokhale <Neha.Gokhale@ibm.com>
it. …
=> #1372 Add a line break when tooltip contains \n

canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx, canvas_modules/common-canvas/src/common-properties/panels/subtabs/subtabs.jsx, canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.jsx
Fixes #1391 
**Interactive component with ARIA role 'dialog' does not have a programmatically associated name**
Before -
After -
**Interactive component with ARIA role 'tabpanel' does not have a programmatically associated name**
Before - 
After -
permitted to submit …
=> #1391 Accessibility: Fixed Properties tearsheet does not have associated name

canvas_modules/common-canvas/__tests__/common-properties/common-properties-test.js, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
fixes #1400 
This can be recreated in the test harness with some changes in App.js using patch: [0001-recreate-issue.patch.zip](https://github.ibm.com/NGP-TWC/wdp-abstract-canvas/files/1114183/0001-recreate-issue.patch.zip) and test flow: `allTypesCanvas.json`
Before fix:
After fix:
by me, under the same open source license …
=> #1400 Updated propertiesConfig are not saved

canvas_modules/common-canvas/src/common-properties/panels/subtabs/subtabs.jsx
Fixes #1450 
Before - 
After -
it.
(d) I understand and agree that …
=> #1450 Accessibility: Fixed The <button> element has the id 'subtabs.tab.0' that is already in use

canvas_modules/common-canvas/__tests__/common-properties/components/title-editor-test.js, canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.jsx, canvas_modules/common-canvas/src/common-properties/form/PropertyDef.js, canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.jsx
Fixes #1458 
After removing `titleDefinition` from `checkbox_paramDef.json` -
Right flyout -
Tearsheet - 
person who certified …
=> #1458 Don’t render properties title when paramDef doesn't have titleDefinition

canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.scss
Fixes #1508 
Horizontal scrollbar was showing up because `properties-sub-tab-container` has width 607px. But `properties-subtabs` has width 639px. This is caused by [CSS](https://github.com/elyra-ai/canvas/pull/1473/files#diff-b91aa08e9d331fac664c0a3ee9f705bd2fb93dc5fb7a6f13f12a782d67ce7fe7R40). Fixed this issue following this thread - https://stackoverflow.com/a/14327156
work with …
=>  #1508 Fixed horizontal scrollbar issue in single category

canvas_modules/common-canvas/src/tooltip/tooltip.jsx, canvas_modules/harness/cypress/e2e/canvas/palette.cy.js
Closes #1533 
- Tooltip closes on blur. If tooltip has a link, tooltip stays open after clicking the link.
- Tooltip closes on scroll
- Tooltip closes on clicking "i" icon again
https://github.com/elyra-ai/canvas/assets/25124000/674537e4-32ec-4b90-89db-25c0f38c730f …
=> #1533 Close properties tooltip on blur 

canvas_modules/common-canvas/__tests__/common-properties/controls/selectcolumns-test.js, canvas_modules/common-canvas/__tests__/common-properties/controls/structuretable-test.js, canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.jsx
=> #1547 Set flexible table height in ‘px’ instead of ‘rem’

canvas_modules/common-canvas/src/common-properties/controls/numberfield/numberfield.jsx
Fixes #1551 
Using this paramDef - 
[Aadistribution.json.zip](https://github.com/elyra-ai/canvas/files/12381893/Aadistribution.json.zip)
https://github.com/elyra-ai/canvas/assets/25124000/28e1dcda-a0b4-4a84-a6eb-21b738785421 …
=> #1551 Disabled numberfield controls should not remain in error state

canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx, canvas_modules/harness/test_resources/parameterDefs/oneofselect_paramDef.json
Closes #1562 
To test this PR, remove `oneofselect_custom_value` from current_parameters - https://github.com/elyra-ai/canvas/blob/main/canvas_modules/harness/test_resources/parameterDefs/oneofselect_paramDef.json#L7
For initial render, verify there's no error message for this control - 
by me, under the same open source …
=> #1562 For oneofselect with custom_value_allowed, don't display error message on initial render

canvas_modules/common-canvas/src/common-properties/properties-controller.js, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx, canvas_modules/common-canvas/src/common-properties/util/property-utils.js, canvas_modules/harness/src/client/App.js
Fixes #1575 
Added a new optional config option `id` in [propertiesInfo object](https://github.com/elyra-ai/canvas/wiki/3.0-Common-Properties-documentation#step-2--set-the-data).
To test this PR, add following code in test harness App.js - https://github.com/elyra-ai/canvas/blob/main/canvas_modules/harness/src/client/App.js#L1940
```
setTimeout(() => {
console.log("Updating paramDef after 30 seconds");
const oldParamDef = this.state.propertiesInfo.parameterDef;
const newParamDef = cloneDeep(oldParamDef);
const uuid = uuid4();
const parameterObj = {
"id": `checkbox-${uuid}`,
"type": "boolean",
"default": true
};
const parameterInfoObj = {
"parameter_ref": `checkbox-${uuid}`,
"label": {
"default": `checkbox-${uuid}`
},
"description": {
"default": "new added checkbox with undefined value"
} …
```
=> #1575 When parameterDef is dynamically updated, don't set INITIAL_LOAD on pre-existing properties

canvas_modules/common-canvas/src/common-canvas/svg-canvas-pipeline.js, canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js, canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-external.js, canvas_modules/harness/assets/images/vector.svg, canvas_modules/harness/src/client/App.js, canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/linkInputToOutputAction.js, canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/mapping-container-node.jsx, canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/mapping.json, canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/react-nodes-mapping-flow.json, canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/react-nodes-mapping.jsx, canvas_modules/harness/src/client/components/custom-canvases/react-nodes-mapping/react-nodes-mapping.scss, canvas_modules/harness/src/client/components/sidepanel/canvas/sidepanel-canvas.jsx, canvas_modules/harness/src/client/constants/constants.js, canvas_modules/harness/src/styles/custom-canvases.scss
=> #1598 Prototype the mapping transformer application

canvas_modules/common-canvas/src/notification-panel/notification-panel.jsx, canvas_modules/common-canvas/src/notification-panel/notification-panel.scss
=> #1619 Notification panel temporarily appearing in test harness

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/checkbox_paramDef.json, canvas_modules/common-canvas/src/common-properties/properties-controller.js, canvas_modules/harness/test_resources/parameterDefs/checkbox_paramDef.json
Fixes #1649 
Added a new parameter to set config options in `setPropertyValues()` method - 
```
/*
* options - optional object of config options where
*   setDefaultValues (boolean): when set to true, set default values from parameter definition
*/
setPropertyValues(values, options)
```
by me, under the same open source …
=> #1649 Added a new parameter in setPropertyValues() to set default properties

canvas_modules/common-canvas/src/color-picker/color-picker.scss, canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss
=> #1664 In dark mode, comments displayed with white background

canvas_modules/common-canvas/__tests__/common-properties/properties-controller-test.js, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/oneofselect_paramDef.json, canvas_modules/common-canvas/src/common-properties/properties-controller.js, canvas_modules/harness/test_resources/parameterDefs/oneofselect_paramDef.json
Fixes #1668 
Added 2 new properties having default values `0` and `" "`. These will be hidden if the `hide` checkbox is selected.
I don't see any issues with setting `0` and `" "` as default values. 
in the …
=> #1668 Fixed bug setDefaultValues not picking up defaults 2nd call onwards

canvas_modules/common-canvas/src/tooltip/tooltip.jsx
Fixes :  #1685 
Close tooltip when clicked on other ui elements other than tooltip and handle tooltip link click scenario.
person …
=> #1685 : Set tooltip visible based on closest for link click

canvas_modules/common-canvas/src/tooltip/tooltip.jsx
=> #1711: Include focus on tooltip link

canvas_modules/common-canvas/src/palette/palette-flyout-content-category.jsx
=>  Display Palette category content using keyboard

canvas_modules/common-canvas/package.json, canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx, canvas_modules/common-canvas/src/common-properties/controls/expression/languages/r-hint.js, canvas_modules/harness/cypress/e2e/properties/expression-control.cy.js
Fixes #1721 
Jest tests are failing with [@codemirror/legacy-modes](https://www.npmjs.com/package/@codemirror/legacy-modes) package as well. To fix jest tests, host applications should add this config in `package.json` file -
```
"jest": {
"transformIgnorePatterns": [
"node_modules/@elyra/canvas/node_modules/(?!@codemirror/legacy-modes)"
]
}
```
work with modifications, whether …
=> #1721 Replace codemirror-lang-r package with @codemirror/legacy-modes

README.md, canvas_modules/common-canvas/package.json
Fixes #1761 
To add documentation link under `Homepage` - https://www.npmjs.com/package/@elyra/canvas …
=> #1761 Add Elyra documentation link in readme and npm

canvas_modules/common-canvas/src/common-properties/controls/passwordfield/passwordfield.jsx
=> #1935 Show/Hide password label is not translated in Passwordfield v13

canvas_modules/common-canvas/src/common-properties/controls/passwordfield/passwordfield.jsx
=> #1935 Show/Hide password label is not translated in Passwordfield v12.x

canvas_modules/common-canvas/src/common-properties/controls/multiselect/multiselect.jsx
Fixes #1945 
Initializing `multiSelectDropdown` in render() was causing the infinite loop.
To fix the issue, created a class variable `this.multiSelectDropdown` in constructor and only update its value when either `selectedOptions` have changed or `controlOpts` have changed in case of filterable Multiselect. 
by me, under …
=> #1945 Fixed multiselect infinite loop after after Carbon v11.57.0 update

canvas_modules/common-canvas/src/common-properties/components/editor-form/editor-form.jsx, canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.jsx, canvas_modules/common-canvas/src/common-properties/components/title-editor/title-editor.scss, canvas_modules/common-canvas/src/common-properties/controls/expression/expression-builder/expression-select-field-function.jsx, canvas_modules/common-canvas/src/common-properties/panels/subtabs/subtabs.jsx
Fixes #1970 
These components were missed during Carbon 11 Migration. Replacing `light` prop with Layer component in **Carbon 11 components only**. 
We will continue using `light` prop in common-properties components like `FlexibleTable, WideFlyout, VirtualizedTable` etc.
by me, under the same open source license (unless I …
=> #1970 Replace light prop with Layer component in Carbon components

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.scss
=> #1949 Code-mirror-replacement text and highlighting doesn't look correct in dark mode

canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js
=> #2093 Text decoration on a Link -- entry area closes when mouse cursor moved out (intermittent).

canvas_modules/common-canvas/__tests__/common-properties/components/title-editor-test.js, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/action_paramDef.json, canvas_modules/common-canvas/src/common-properties/form/EditorForm.js, canvas_modules/common-canvas/src/common-properties/form/Form.js, canvas_modules/harness/test_resources/parameterDefs/action_paramDef.json
closes #2088
Additional changes to render actions in the title editor that are not defined in group_info …
=> #2088 Render actions in title outside of groups

canvas_modules/common-canvas/__tests__/common-properties/controls/oneofselect-test.js, canvas_modules/common-canvas/src/common-properties/controls/dropdown/dropdown.jsx
=> #2108 Need shouldFilterItem support for oneofselect control

canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-external.js
closes #2072 
The current check for `createRoot` was causing builds to fail with `ba.createRoot is not a function` when attempting to use a jsx element as an image for a node, as `createRoot` still returned a value on prior versions. This change explicitly checks the react version to make sure `createRoot` is only use if React 18 is being used, otherwise it will use `ReactDOM.render` …
=> #2072 fix: added explicit check for react version

canvas_modules/harness/src/client/components/custom-canvases/parallax/parallax.scss
=> #2105 Parallax sample app does not look good in dark mode

canvas_modules/harness/cypress/e2e/properties/actions.cy.js
Fixes #2189 
Cypress test was failing because first `cy.hoverOverActionImage("fall");` works fine. But next `cy.hoverOverActionImage("spring");` fails. Mouse never goes over spring action image.
To fix the test, moved mouse elsewhere before calling `cy.hoverOverActionImage("spring");` .
by me, under the same open source …
=> #2189 Fixed actions image cypress test

canvas_modules/common-canvas/src/common-canvas/svg-canvas-d3.scss, canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-textarea.js, canvas_modules/harness/cypress/support/canvas/comments-cmds.js
=> #2207 Scrollbar for WYSIWYG annotation note can not be clicked to scroll

canvas_modules/harness/cypress/e2e/canvas/zoom.cy.js, canvas_modules/harness/cypress/support/canvas/verification-cmds.js
=> #2238 Write function to compare transform string in Cypress tests

canvas_modules/common-canvas/src/common-canvas/cc-bottom-panel.jsx, canvas_modules/common-canvas/src/common-canvas/cc-right-flyout.jsx, canvas_modules/harness/cypress/e2e/canvas/bottom-panel.cy.js
=> #2244 Dragging Bottom Panel beyond its max height hides Right Flyout Buttons

canvas_modules/common-canvas/src/common-canvas/cc-bottom-panel.jsx
=> #2246 Dragging Bottom Panel beyond its Max Height with Top Panel open hides Right Flyout Buttons

canvas_modules/common-canvas/src/common-canvas/canvas-controller.js, canvas_modules/common-canvas/src/object-model/object-model.js, canvas_modules/common-canvas/src/object-model/redux/reducers/breadcrumbs.js
=> #2254 setPipelineFlow cannot work when only primary_pipeline changed

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js, canvas_modules/common-canvas/src/common-canvas/constants/canvas-constants.js, canvas_modules/common-canvas/src/common-canvas/svg-canvas-renderer.js, canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-new-link.js, canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-canvas.jsx, canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-flow.json, canvas_modules/harness/src/client/components/custom-canvases/prompt/prompt-react.jsx
=> #2276 Allow click on a port to cause an action

canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
=> #2264 Common Properties Button is hidden on height change

canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
Fixes: #2287 
Use this code to reproduce the issue - https://github.com/samueldmeyer/canvas/commit/cdd1af1f4aafe42f4a7ff5db771c1e3354930a24
https://github.com/user-attachments/assets/3f5f3f32-5132-4a72-bffe-c2f535ad4b86
permitted to submit under a different license), as …
=>  #2287 Fixed Common properties callbacks don't update on re-render

docs/pages/04-common-properties.md
=> #2289 Common Properties Right Flyout Styling Documentation

canvas_modules/common-canvas/__tests__/common-properties/controls/structurelisteditor-test.js, canvas_modules/common-canvas/__tests__/test_resources/paramDefs/structurelisteditor_paramDef.json, canvas_modules/common-canvas/src/common-properties/components/flexible-table/flexible-table.scss, canvas_modules/common-canvas/src/common-properties/components/table-toolbar/table-toolbar.jsx, canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx, canvas_modules/common-canvas/src/common-properties/controls/list/list.jsx, canvas_modules/common-canvas/src/common-properties/controls/selectcolumns/selectcolumns.jsx, canvas_modules/harness/test_resources/parameterDefs/structurelisteditor_paramDef.json
Fixes: #2292
Both of these screenshots are from `structurelisteditor_paramDef.json`.
When single select table has `moveable_rows: true`, table toolbar should have row move buttons -
When moveable_rows: false or moveable_rows is not set, don't show table toolbar for single select tables -
by me, under the same open source …
=> #2292 For single select tables, show table toolbar when moveable_rows is set

canvas_modules/common-canvas/src/common-canvas/common-canvas-utils.js, canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-new-link.js, canvas_modules/common-canvas/src/common-canvas/svg-canvas-utils-drag-objects.js
=> #2298 Drag interactions are too sensitive

canvas_modules/common-canvas/src/common-properties/controls/abstract-table.jsx
=> #2300 Readonly table row should not have delete icon

canvas_modules/common-canvas/__tests__/object-model/object-model-redux-test.js, canvas_modules/common-canvas/src/object-model/object-model.js
=> #2302 Nodes with looped links crash the UI

canvas_modules/common-canvas/types/common-canvas.ts
=> #2483 Cannot use CanvasController when it is exported only as a type

canvas_modules/common-canvas/src/common-properties/controls/expression/expression.scss
=> #2539 Text in suggestion dropdown list for expression builder in node property window has no contrast in Dark mode

canvas_modules/common-canvas/__tests__/common-properties/controls/custom-test.js, canvas_modules/common-canvas/src/common-properties/properties-main/properties-main.jsx
Fixes: #2541 
When `customControls` are undefined, following error will be shown -
person who certified (a), (b) or (c) and I have …
=> #2541 Improve error message when customControls are forgotten

canvas_modules/common-canvas/types/common-properties.ts
- Fixed an issue that causes a build bream when isolatedModules is enabled.
person who certified (a), (b) or (c) and I have not …
=> Build failing with: error TS1205: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.
